; Generated by generate_quake_alias_visibility.py; do not edit.
.segment "BSP_ALIAS_VISIBILITY_ENABLED"
QuakeBSPAliasVisibilityEnabled:
        .incbin "Data/QuakeBSPAliasVisibilityEnabled.bin"
QuakeBSPAliasVisibilityEnabledEnd:
.assert QuakeBSPAliasVisibilityEnabledEnd - QuakeBSPAliasVisibilityEnabled = $8000, error, "Enabled alias visibility must fill one halfbank"
.assert __BSP_ALIAS_VISIBILITY_ENABLED_LOAD__ = $6F0000, lderror, "Enabled alias visibility moved"

.segment "BSP_ALIAS_VISIBILITY_DISABLED"
QuakeBSPAliasVisibilityDisabled:
        .incbin "Data/QuakeBSPAliasVisibilityDisabled.bin"
QuakeBSPAliasVisibilityDisabledEnd:
.assert QuakeBSPAliasVisibilityDisabledEnd - QuakeBSPAliasVisibilityDisabled = $8000, error, "Disabled alias visibility must fill one halfbank"
.assert __BSP_ALIAS_VISIBILITY_DISABLED_LOAD__ = $6F8000, lderror, "Disabled alias visibility moved"
