#!/usr/bin/env python3
"""Generate the configured real-time 8 kHz SNES Quake sound package."""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import struct
import sys
import time
from concurrent.futures import ProcessPoolExecutor
from pathlib import Path

from workspace_paths import shared_tools_root, workspace_root
from typing import Any, Sequence


TOOLS = Path(__file__).resolve().parent
SHARED_TOOLS = shared_tools_root(__file__)
for dependency in (TOOLS, SHARED_TOOLS):
    if str(dependency) not in sys.path:
        sys.path.insert(0, str(dependency))

from snes_tooling.shared.generated_outputs import (  # noqa: E402
    GeneratedOutputError,
    OwnedFileFamily,
    sync_generated_outputs,
)
import generate_quake_bsp as bsp_tools  # noqa: E402
from host_resources import physical_core_count  # noqa: E402
from quake_rom_config import (  # noqa: E402
    DEFAULT_CONFIG,
    configured_playback_sample_rate,
    configured_soundtrack,
    resolve_configured_demo,
)
from quake_snes_realtime_sound import (  # noqa: E402
    CACHE_CHUNK_CAPACITY,
    CHUNK_BYTES,
    CHUNK_TRANSFER_PACKETS,
    DSP_PITCH,
    MIX_COMMAND_COMPLETE,
    MIX_COMMAND_START,
    MIX_COMMAND_STOP,
    MIX_COMMAND_VOLUME,
    OUTPUT_RATE_HZ,
    SAMPLE_FLAG_LOOP,
    STREAM_BUFFER_COUNT,
    UPLOAD_FLAG_TERMINAL,
    VOICE_COUNT,
    EncodedSound,
    MixCommand,
    build_mix_schedule,
    encode_sound,
    select_cached_sounds,
)
from quake_snes_soundtrack import (  # noqa: E402
    BRR_PCM_HEADROOM,
    decode_precise_listeners,
    fnv1a64,
    load_waves,
)
from quake_sound_replay import (  # noqa: E402
    decode_sound_replay,
    encode_sound_replay,
    extract_canonical_sound_replay,
)


DEFAULT_OUTPUT = workspace_root(__file__) / "src/snes_quake/Data"
REPLAY_NAME = Path("QuakeBSPReferenceSoundReplay.bin")
CAMERA_NAME = Path("QuakeBSPDemoPrecise.bin")
TIMING_NAME = Path("QuakeBSPDemoPreciseTiming.bin")
INCLUDE_NAME = Path("QuakeBSPSoundtrack.i")
ASSEMBLY_NAME = Path("QuakeBSPSoundtrackAssets.s")
METADATA_NAME = Path("QuakeBSPSoundtrack.json")
SAMPLE_DIRECTORY_NAME = Path("QuakeBSPSoundtrackSampleDirectory.bin")
CACHE_DIRECTORY_NAME = Path("QuakeBSPSoundtrackCacheDirectory.bin")
SCHEDULE_NAME = Path("QuakeBSPSoundtrackSchedule.bin")
BANK_PREFIX = "QuakeBSPSoundtrackBank"
ROM_BANK_BYTES = 0x8000
FIRST_ROM_BANK = 98
AVAILABLE_ROM_BANKS = 30
PREMIX_BANK_COUNT = 22
RECLAIMED_BANKS_REUSED_BY_GSU = 1
CHUNKS_PER_BANK = ROM_BANK_BYTES // CHUNK_BYTES
SAMPLE_DIRECTORY_RECORD = struct.Struct("<HHBBH")
MIX_COMMAND_RECORD = struct.Struct("<HBBBBBB")
OWNED_OUTPUTS = (
    OwnedFileFamily(prefix="QuakeBSPSoundtrack", suffix=".bin"),
    OwnedFileFamily(prefix="QuakeBSPSoundtrack", suffix=".i"),
    OwnedFileFamily(prefix="QuakeBSPSoundtrackAssets", suffix=".s"),
    OwnedFileFamily(prefix="QuakeBSPSoundtrack", suffix=".json"),
)


def _sha256(payload: bytes) -> str:
    return hashlib.sha256(payload).hexdigest()


def _file_record(path: Path, payload: bytes) -> dict[str, Any]:
    return {
        "path": path.as_posix(),
        "bytes": len(payload),
        "sha256": _sha256(payload),
    }


def _config_record(path: Path) -> dict[str, Any]:
    return _file_record(Path(path.name), path.read_bytes())


def _render_include(contract: dict[str, int]) -> bytes:
    lines = [
        "; Generated by generate_quake_snes_soundtrack.py.",
        "; Do not edit by hand.",
        "",
    ]
    for name, value in contract.items():
        rendered = (
            f"${value:X}"
            if name.endswith(("_PITCH", "_SIGNATURE", "_DELTA"))
            else str(value)
        )
        lines.append(f"{name} = {rendered}")
    lines.extend(
        (
            "",
            '.assert BSP_SOUND_OUTPUT_RATE_HZ = 8000, error, "realtime mixer requires 8 kHz sources"',
            '.assert BSP_SOUND_VOICE_COUNT = 8, error, "realtime mixer requires all S-DSP voices"',
            '.assert BSP_SOUND_STREAM_CHUNK_BYTES .mod 3 = 0, error, "sound chunks must use whole three-byte packets"',
            '.assert BSP_SOUND_STREAM_BUFFER_COUNT = 4, error, "realtime mixer requires four stream buffers per voice"',
            '.assert BSP_SOUND_BANK_COUNT <= 12, error, "realtime source package exceeds twelve halfbanks"',
            "",
        )
    )
    return "\n".join(lines).encode("ascii")


def _render_assembly(
    bank_payloads: Sequence[bytes],
    chunk_count: int,
    tail_bytes: int,
) -> bytes:
    lines = [
        "; Generated by generate_quake_snes_soundtrack.py.",
        "; Do not edit by hand.",
        "",
    ]
    for bank, payload in enumerate(bank_payloads):
        lines.extend(
            (
                f'.segment "BSP_SOUND_{bank:02d}"',
                f"QuakeBSPSoundtrackBank{bank:02d}:",
                f'        .incbin "Data/{BANK_PREFIX}{bank:02d}.bin"',
                f"QuakeBSPSoundtrackBank{bank:02d}PayloadEnd:",
                f'.assert QuakeBSPSoundtrackBank{bank:02d}PayloadEnd - QuakeBSPSoundtrackBank{bank:02d} = {len(payload)}, error, "sound bank payload size disagrees"',
                "",
            )
        )
    if not bank_payloads:
        return "\n".join(lines).encode("ascii")
    final_bank = len(bank_payloads) - 1
    lines.extend(
        (
            f'.segment "BSP_SOUND_{final_bank:02d}"',
            "QuakeBSPSoundChunkDirectory:",
        )
    )
    for chunk in range(chunk_count):
        bank = chunk // CHUNKS_PER_BANK
        offset = chunk % CHUNKS_PER_BANK * CHUNK_BYTES
        lines.extend(
            (
                f"        .faraddr QuakeBSPSoundtrackBank{bank:02d}+{offset}",
                "        .byte 0",
            )
        )
    lines.extend(
        (
            "QuakeBSPSoundChunkDirectoryEnd:",
            f'.assert QuakeBSPSoundChunkDirectoryEnd - QuakeBSPSoundChunkDirectory = {chunk_count * 4}, error, "sound chunk directory size disagrees"',
            "QuakeBSPSoundSampleDirectory:",
            f'        .incbin "Data/{SAMPLE_DIRECTORY_NAME.as_posix()}"',
            "QuakeBSPSoundSampleDirectoryEnd:",
            "QuakeBSPSoundCacheDirectory:",
            f'        .incbin "Data/{CACHE_DIRECTORY_NAME.as_posix()}"',
            "QuakeBSPSoundCacheDirectoryEnd:",
            "QuakeBSPSoundMixSchedule:",
            f'        .incbin "Data/{SCHEDULE_NAME.as_posix()}"',
            "QuakeBSPSoundMixScheduleEnd:",
            f'.assert QuakeBSPSoundMixScheduleEnd - QuakeBSPSoundtrackBank{final_bank:02d} = {tail_bytes}, error, "sound tail-bank accounting disagrees"',
            f'.assert QuakeBSPSoundMixScheduleEnd - QuakeBSPSoundtrackBank{final_bank:02d} <= $8000, lderror, "realtime sound metadata exceeds final bank"',
            "",
        )
    )
    return "\n".join(lines).encode("ascii")


def _disabled_outputs(
    *,
    config_path: Path,
    demo: Any,
    replay_payload: bytes,
    camera_payload: bytes,
    sample_rate_hz: int,
    volume: float,
) -> tuple[dict[Path, bytes], dict[str, Any]]:
    contract = {
        "BSP_SOUND_ENABLED": 0,
        "BSP_SOUND_OUTPUT_RATE_HZ": sample_rate_hz,
        "BSP_SOUND_VOLUME_Q8": round(volume * 256),
        "BSP_SOUND_VOICE_COUNT": VOICE_COUNT,
        "BSP_SOUND_SAMPLE_COUNT": 0,
        "BSP_SOUND_SOURCE_EVENT_COUNT": 0,
        "BSP_SOUND_MIX_COMMAND_COUNT": 0,
        "BSP_SOUND_MIX_COMMAND_BYTES": MIX_COMMAND_RECORD.size,
        "BSP_SOUND_DURATION_TICKS": 0,
        "BSP_SOUND_STREAM_CHUNK_BYTES": CHUNK_BYTES,
        "BSP_SOUND_STREAM_CHUNK_PACKETS": CHUNK_TRANSFER_PACKETS,
        "BSP_SOUND_STREAM_CHUNK_COUNT": 0,
        "BSP_SOUND_STREAM_BUFFER_COUNT": STREAM_BUFFER_COUNT,
        "BSP_SOUND_CACHE_CHUNK_COUNT": 0,
        "BSP_SOUND_BANK_COUNT": 0,
        "BSP_SOUND_DSP_PITCH": DSP_PITCH,
        "BSP_SOUND_PROTOCOL_SIGNATURE": 0xC0,
        "BSP_SOUND_PROTOCOL_MASK": 0xC0,
        "BSP_SOUND_CPU_MIRROR_DELTA": 0x300000,
        "BSP_SOUND_CPU_MIRROR_BANK_DELTA": 0x30,
    }
    include = _render_include(contract)
    assembly = _render_assembly((), 0, 0)
    metadata: dict[str, Any] = {
        "schema": "quake-snes-realtime-sound-v2",
        "enabled": False,
        "reason": "disabled by ROM configuration",
        "source": {
            "config": _config_record(config_path),
            "demo": demo.metadata(),
            "soundReplay": _file_record(REPLAY_NAME, replay_payload),
            "cameraTrack": _file_record(CAMERA_NAME, camera_payload),
        },
        "format": contract,
    }
    outputs = {INCLUDE_NAME: include, ASSEMBLY_NAME: assembly}
    metadata["output"] = {
        path.as_posix(): _file_record(path, payload)
        for path, payload in outputs.items()
    }
    outputs[METADATA_NAME] = (
        json.dumps(metadata, indent=2, sort_keys=True) + "\n"
    ).encode("ascii")
    return outputs, metadata


def _encode_source_task(task: tuple[int, Any]) -> EncodedSound:
    return encode_sound(*task)


def _encode_sources(waves: Sequence[Any], workers: int) -> tuple[EncodedSound, ...]:
    if workers <= 0:
        raise ValueError("BRR worker count must be positive")
    tasks = tuple(enumerate(waves))
    if workers == 1:
        return tuple(_encode_source_task(task) for task in tasks)
    with ProcessPoolExecutor(max_workers=min(workers, len(tasks))) as executor:
        return tuple(executor.map(_encode_source_task, tasks, chunksize=1))


def _encode_schedule(commands: Sequence[MixCommand]) -> bytes:
    payload = bytearray()
    for command in commands:
        if (
            not 0 <= command.due_tick <= 0xFFFF
            or command.opcode
            not in (
                MIX_COMMAND_START,
                MIX_COMMAND_STOP,
                MIX_COMMAND_VOLUME,
                MIX_COMMAND_COMPLETE,
            )
            or not 0 <= command.voice <= 0xFF
            or not 0 <= command.sound_slot <= 0xFF
            or not 0 <= command.left <= 0x7F
            or not 0 <= command.right <= 0x7F
        ):
            raise ValueError("realtime sound command exceeds its binary record")
        payload.extend(
            MIX_COMMAND_RECORD.pack(
                command.due_tick,
                command.opcode,
                command.voice,
                command.sound_slot,
                command.left,
                command.right,
                0,
            )
        )
    return bytes(payload)


def build_outputs(
    pak_path: Path,
    *,
    config_path: Path = DEFAULT_CONFIG,
    output_dir: Path = DEFAULT_OUTPUT,
    workers: int | None = None,
) -> tuple[dict[Path, bytes], dict[str, Any]]:
    config_path = config_path.resolve()
    output_dir = output_dir.resolve()
    sound = configured_soundtrack(config_path)
    playback_rate = configured_playback_sample_rate(config_path)
    archive = bsp_tools.PakArchive(pak_path)
    demo = resolve_configured_demo(archive.read, config_path)
    replay_payload = (output_dir / REPLAY_NAME).read_bytes()
    expected_replay = encode_sound_replay(
        extract_canonical_sound_replay(demo.payload, demo.map_entry, playback_rate)
    )
    if replay_payload != expected_replay:
        raise ValueError(
            "reference sound replay is stale for the configured demo; regenerate "
            "the complete asset chain"
        )
    replay = decode_sound_replay(replay_payload)
    camera_payload = (output_dir / CAMERA_NAME).read_bytes()
    if replay.camera_track_fnv1a64 != fnv1a64(camera_payload):
        raise ValueError("reference sound replay disagrees with precise camera track")
    if sound.sample_rate_hz != OUTPUT_RATE_HZ:
        raise ValueError("real-time SNES mixer requires sound.sampleRateHz = 8000")
    if not sound.enabled:
        return _disabled_outputs(
            config_path=config_path,
            demo=demo,
            replay_payload=replay_payload,
            camera_payload=camera_payload,
            sample_rate_hz=sound.sample_rate_hz,
            volume=sound.volume,
        )

    timing_payload = (output_dir / TIMING_NAME).read_bytes()
    if len(timing_payload) % 2:
        raise ValueError("precise demo timing is not uint16 aligned")
    timing_ticks = struct.unpack(f"<{len(timing_payload) // 2}H", timing_payload)
    waves = load_waves(replay, archive.read)
    listeners = decode_precise_listeners(camera_payload)
    selected_workers = physical_core_count() if workers is None else workers
    encoded = _encode_sources(waves, selected_workers)
    schedule = build_mix_schedule(
        replay,
        waves,
        listeners,
        timing_ticks,
        volume=sound.volume,
    )
    cached_slots = select_cached_sounds(encoded, schedule)
    cached_set = frozenset(cached_slots)

    flattened: list[bytes] = []
    first_chunks: list[int] = []
    for source in encoded:
        first_chunks.append(len(flattened))
        flattened.extend(source.chunks)
    bank_payloads = tuple(
        b"".join(flattened[offset : offset + CHUNKS_PER_BANK])
        for offset in range(0, len(flattened), CHUNKS_PER_BANK)
    )
    if len(bank_payloads) > 12:
        raise ValueError("8 kHz source chunks exceed the twelve-bank package")

    cache_chunk_ids: list[int] = []
    cache_first: dict[int, int] = {}
    for slot in cached_slots:
        cache_first[slot] = len(cache_chunk_ids)
        cache_chunk_ids.extend(
            range(first_chunks[slot], first_chunks[slot] + len(encoded[slot].chunks))
        )
    if len(cache_chunk_ids) > CACHE_CHUNK_CAPACITY:
        raise AssertionError("selected hot-sample cache exceeds ARAM capacity")
    cache_directory = b"".join(struct.pack("<H", value) for value in cache_chunk_ids)

    sample_directory = bytearray()
    for source in encoded:
        flags = SAMPLE_FLAG_LOOP if source.loop_start is not None else 0
        sample_directory.extend(
            SAMPLE_DIRECTORY_RECORD.pack(
                first_chunks[source.slot],
                len(source.chunks),
                cache_first.get(source.slot, 0xFF),
                flags,
                source.loop_chunk if source.loop_chunk is not None else 0xFFFF,
            )
        )
    schedule_payload = _encode_schedule(schedule.commands)
    chunk_directory_bytes = len(flattened) * 4
    final_bank_bytes = (
        len(bank_payloads[-1])
        + chunk_directory_bytes
        + len(sample_directory)
        + len(cache_directory)
        + len(schedule_payload)
    )
    if final_bank_bytes > ROM_BANK_BYTES:
        raise ValueError("realtime sound directories exceed the final source bank")

    contract = {
        "BSP_SOUND_ENABLED": 1,
        "BSP_SOUND_OUTPUT_RATE_HZ": OUTPUT_RATE_HZ,
        "BSP_SOUND_VOLUME_Q8": round(sound.volume * 256),
        "BSP_SOUND_VOICE_COUNT": VOICE_COUNT,
        "BSP_SOUND_SAMPLE_COUNT": len(encoded),
        "BSP_SOUND_SOURCE_EVENT_COUNT": schedule.processed_events,
        "BSP_SOUND_MIX_COMMAND_COUNT": len(schedule.commands),
        "BSP_SOUND_MIX_COMMAND_BYTES": MIX_COMMAND_RECORD.size,
        "BSP_SOUND_DURATION_TICKS": schedule.duration_ticks,
        "BSP_SOUND_STREAM_CHUNK_BYTES": CHUNK_BYTES,
        "BSP_SOUND_STREAM_CHUNK_PACKETS": CHUNK_TRANSFER_PACKETS,
        "BSP_SOUND_STREAM_CHUNK_COUNT": len(flattened),
        "BSP_SOUND_STREAM_BUFFER_COUNT": STREAM_BUFFER_COUNT,
        "BSP_SOUND_CACHE_CHUNK_COUNT": len(cache_chunk_ids),
        "BSP_SOUND_BANK_COUNT": len(bank_payloads),
        "BSP_SOUND_DSP_PITCH": DSP_PITCH,
        "BSP_SOUND_PROTOCOL_SIGNATURE": 0xC0,
        "BSP_SOUND_PROTOCOL_MASK": 0xC0,
        "BSP_SOUND_CPU_MIRROR_DELTA": 0x300000,
        "BSP_SOUND_CPU_MIRROR_BANK_DELTA": 0x30,
    }
    include = _render_include(contract)
    assembly = _render_assembly(bank_payloads, len(flattened), final_bank_bytes)
    outputs: dict[Path, bytes] = {
        INCLUDE_NAME: include,
        ASSEMBLY_NAME: assembly,
        SAMPLE_DIRECTORY_NAME: bytes(sample_directory),
        CACHE_DIRECTORY_NAME: cache_directory,
        SCHEDULE_NAME: schedule_payload,
    }
    for index, payload in enumerate(bank_payloads):
        outputs[Path(f"{BANK_PREFIX}{index:02d}.bin")] = payload

    waveform_audit = []
    for slot, (name, wave, source) in enumerate(
        zip(replay.sound_names, waves, encoded, strict=True)
    ):
        payload = archive.read("sound/" + name)
        encoded_values = max(1, source.encoded_samples)
        waveform_audit.append(
            {
                "slot": slot,
                "name": name,
                "bytes": len(payload),
                "sha256": _sha256(payload),
                "sourceSampleRateHz": wave.sample_rate_hz,
                "sourceSampleCount": len(wave.samples),
                "outputSampleRateHz": OUTPUT_RATE_HZ,
                "outputSampleCount": source.source_samples,
                "loopStart": wave.loop_start,
                "outputLoopStart": source.loop_start,
                "chunkCount": len(source.chunks),
                "initialChunkCount": source.initial_chunk_count,
                "loopChunk": source.loop_chunk,
                "residentBytes": source.payload_bytes,
                "cached": slot in cached_set,
                "cacheFirstChunk": cache_first.get(slot),
                "rmsError": math.sqrt(source.squared_error / encoded_values),
                "peakError": source.peak_error,
            }
        )

    directory_bytes = (
        chunk_directory_bytes + len(sample_directory) + len(cache_directory)
    )
    payload_bytes = sum(len(payload) for payload in bank_payloads)
    used_bytes = payload_bytes + directory_bytes + len(schedule_payload)
    metadata = {
        "schema": "quake-snes-realtime-sound-v2",
        "enabled": True,
        "source": {
            "config": _config_record(config_path),
            "demo": demo.metadata(),
            "soundReplay": _file_record(REPLAY_NAME, replay_payload),
            "cameraTrack": _file_record(CAMERA_NAME, camera_payload),
            "timingTrack": _file_record(TIMING_NAME, timing_payload),
            "waves": waveform_audit,
        },
        "format": {
            **contract,
            "mode": "eight-voice S-DSP realtime mixer",
            "channelsPerSource": 1,
            "brrPcmHeadroom": BRR_PCM_HEADROOM,
            "chunkSamples": CHUNK_BYTES // 9 * 16,
            "chunkSeconds": CHUNK_BYTES / 9 * 16 / OUTPUT_RATE_HZ,
            "romFirstBank": FIRST_ROM_BANK,
            "romLastBank": FIRST_ROM_BANK + len(bank_payloads) - 1,
            "streamBufferBytes": VOICE_COUNT * STREAM_BUFFER_COUNT * CHUNK_BYTES,
            "cacheBytes": len(cache_chunk_ids) * CHUNK_BYTES,
            "cacheSampleCount": len(cached_slots),
            "cacheSoundSlots": list(cached_slots),
        },
        "package": {
            "sourcePayloadBytes": payload_bytes,
            "directoryBytes": directory_bytes,
            "scheduleBytes": len(schedule_payload),
            "usedBytes": used_bytes,
            "allocatedBytes": len(bank_payloads) * ROM_BANK_BYTES,
            "soundReservedButUnusedBanks": AVAILABLE_ROM_BANKS - len(bank_payloads),
            "reusedByGsuBanks": RECLAIMED_BANKS_REUSED_BY_GSU,
            "freeTailBanks": AVAILABLE_ROM_BANKS
            - len(bank_payloads)
            - RECLAIMED_BANKS_REUSED_BY_GSU,
            "reclaimedBanksFromPremix": PREMIX_BANK_COUNT - len(bank_payloads),
            "reclaimedFreeBanksFromPremix": PREMIX_BANK_COUNT
            - len(bank_payloads)
            - RECLAIMED_BANKS_REUSED_BY_GSU,
            "reclaimedBytesFromPremix": (PREMIX_BANK_COUNT - len(bank_payloads))
            * ROM_BANK_BYTES,
        },
        "mix": {
            "policy": "precomputed deterministic allocation; native S-DSP volumes and summation",
            "processedEvents": schedule.processed_events,
            "sourceStarts": schedule.source_starts,
            "sourceStatics": schedule.source_statics,
            "sourceStops": schedule.source_stops,
            "inaudibleEvents": schedule.inaudible_events,
            "hardwareStarts": schedule.hardware_starts,
            "hardwareStops": schedule.hardware_stops,
            "hardwareSteals": schedule.hardware_steals,
            "staticRestarts": schedule.static_restarts,
            "volumeUpdates": schedule.volume_updates,
            "peakActiveVoices": schedule.peak_active_voices,
            "commandCount": len(schedule.commands),
            "commandOpcodes": {
                "start": MIX_COMMAND_START,
                "stop": MIX_COMMAND_STOP,
                "volume": MIX_COMMAND_VOLUME,
                "complete": MIX_COMMAND_COMPLETE,
            },
            "uploadTerminalFlag": UPLOAD_FLAG_TERMINAL,
        },
    }
    metadata["output"] = {
        path.as_posix(): _file_record(path, payload)
        for path, payload in outputs.items()
    }
    outputs[METADATA_NAME] = (
        json.dumps(metadata, indent=2, sort_keys=True) + "\n"
    ).encode("ascii")
    return outputs, metadata


def parse_args(argv: Sequence[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--pak", type=Path)
    parser.add_argument("--config", type=Path, default=DEFAULT_CONFIG)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--workers", type=int)
    parser.add_argument("--check", action="store_true")
    return parser.parse_args(argv)


def main(argv: Sequence[str] | None = None) -> int:
    started = time.monotonic()
    args = parse_args(argv)
    try:
        if args.workers is not None and args.workers <= 0:
            raise ValueError("--workers must be positive")
        outputs, metadata = build_outputs(
            bsp_tools.locate_quake_pak(args.pak),
            config_path=args.config,
            output_dir=args.output,
            workers=args.workers,
        )
        sync_generated_outputs(
            outputs,
            args.output,
            check=args.check,
            owned_families=OWNED_OUTPUTS,
        )
    except KeyboardInterrupt:
        print(
            "Quake SNES realtime sound interrupted: "
            f"elapsed={time.monotonic() - started:.3f}s",
            file=sys.stderr,
        )
        return 130
    except (GeneratedOutputError, OSError, RuntimeError, ValueError) as error:
        print(
            f"error: {error}; elapsed={time.monotonic() - started:.3f}s",
            file=sys.stderr,
        )
        return 1
    action = "verified" if args.check else "generated"
    contract = metadata["format"]
    print(
        f"Quake SNES realtime sound {action}: enabled={metadata['enabled']} "
        f"events={contract['BSP_SOUND_SOURCE_EVENT_COUNT']} "
        f"commands={contract['BSP_SOUND_MIX_COMMAND_COUNT']} "
        f"banks={contract['BSP_SOUND_BANK_COUNT']} "
        f"elapsed={time.monotonic() - started:.3f}s"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
