#!/usr/bin/env python3
"""Publish canonical inline-brush state for the configured Quake demo."""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
import time
from collections import defaultdict
from dataclasses import replace
from pathlib import Path
from typing import Any

from workspace_paths import shared_tools_root, workspace_root


TOOLS_DIR = Path(__file__).resolve().parent
SHARED_TOOLS_DIR = shared_tools_root(__file__)
for dependency_dir in (TOOLS_DIR, SHARED_TOOLS_DIR):
    if str(dependency_dir) not in sys.path:
        sys.path.insert(0, str(dependency_dir))

from snes_tooling.shared.generated_outputs import (  # noqa: E402
    GeneratedOutputError,
    OwnedFileFamily,
    sync_generated_outputs,
)
import generate_quake_bsp as bsp_tools  # noqa: E402
from quake_bsp_brush_assets import (  # noqa: E402
    build_brush_assets,
    derive_demo_visible_replay,
    prepare_brush_source,
)
from quake_brush_replay import (  # noqa: E402
    BRUSH_REPLAY_HEADER,
    BRUSH_REPLAY_SNAPSHOT,
    BRUSH_REPLAY_STATE,
    BRUSH_REPLAY_STEP_RATE_HZ,
    BRUSH_REPLAY_VERSION,
    BrushEntityState,
    CanonicalBrushReplay,
    decode_brush_replay,
    encode_precise_camera_track,
    encode_brush_replay,
    extract_canonical_brush_replay,
    fnv1a64,
    step_row_indices,
)
from quake_rom_config import (  # noqa: E402
    DEFAULT_CONFIG,
    DEFAULT_PLAYBACK_SAMPLE_RATE_HZ,
    DemoSource,
    configured_playback_sample_rate,
    resolve_configured_demo,
    resolve_demo_source,
)
from quake_external_bsp_replay import (  # noqa: E402
    encode_external_bsp_replay,
    extract_canonical_external_bsp_replay,
)
from quake_external_bsp_snes import (  # noqa: E402
    encode_external_active_rows,
    load_brush_direct_safety_profile,
    load_external_visibility_profile,
)


DEFAULT_OUTPUT = workspace_root(__file__) / "src/snes_quake/Data"
STREAM_NAME = Path("QuakeBSPBrushReplay.bin")
METADATA_NAME = Path("QuakeBSPBrushReplay.json")
ASSET_METADATA_NAME = Path("QuakeBSPBrushAssets.json")
ASSET_INCLUDE_NAME = Path("QuakeBSPBrushAssets.i")
OWNED_OUTPUTS = (
    OwnedFileFamily(prefix="QuakeBSPBrushReplay", suffix=".bin"),
    OwnedFileFamily(prefix="QuakeBSPBrushReplay", suffix=".json"),
    OwnedFileFamily(prefix="QuakeBSPBrushAssets", suffix=".json"),
    OwnedFileFamily(prefix="QuakeBSPBrushAssets", suffix=".i"),
    OwnedFileFamily(prefix="QuakeBSPBrushRuntime", suffix=".bin", numbered=True),
    OwnedFileFamily(prefix="QuakeBSPBrushTexturePixels", suffix=".bin", numbered=True),
    OwnedFileFamily(prefix="QuakeBSPBrushFragments", suffix=".bin", numbered=True),
)
MOVING_BRUSH_CLASSES = ("func_button", "func_door", "func_plat", "func_train")


def asset_include(metadata: dict[str, Any]) -> bytes:
    runtime = metadata["runtime"]
    fragments = metadata["worldComposition"]["fragments"]
    roles = fragments["bankRoles"]
    dynamic_replay_supported = bool(metadata["runtimeReplay"]["supported"])
    external = metadata["visualStates"]["externalBsp"]
    external_source = metadata["source"].get("externalBsp", {})
    external_replay = external_source.get("replay", {})
    external_models = external_source.get("models", {})
    link_bounds = metadata["visualStates"]["fragmentLinkBounds"]
    fly_link_max = (
        link_bounds["flyCombinedMaximumNonSolidLinks"]
        if dynamic_replay_supported
        else 0
    )
    fly_leaf_marker_max = (
        link_bounds["flyCombinedMaximumLeafMarkers"] if dynamic_replay_supported else 0
    )
    fly_group_fragment_max = (
        link_bounds["flyCombinedMaximumLeafGroupFragments"]
        if dynamic_replay_supported
        else 0
    )
    fly_group_projected_vertex_max = (
        link_bounds["flyCombinedMaximumLeafGroupProjectedVertices"]
        if dynamic_replay_supported
        else 0
    )
    lines = [
        "; Generated by generate_quake_brush_replay.py; do not edit.",
        f"BSP_BRUSH_ASSET_VERSION = {metadata['version']}",
        (f"BSP_BRUSH_DYNAMIC_REPLAY_SUPPORTED = {int(dynamic_replay_supported)}"),
        f"BSP_EXTERNAL_BSP_SUPPORTED = {int(external['supported'])}",
        f"BSP_EXTERNAL_BSP_ENTITY_SLOT_FIRST = {external['firstEntitySlot']}",
        f"BSP_EXTERNAL_BSP_ENTITY_SLOT_COUNT = {external['entitySlotCount']}",
        (
            "BSP_EXTERNAL_BSP_INLINE_MODEL_FIRST = "
            f"{external_replay.get('firstInlineModel', 0)}"
        ),
        (
            "BSP_EXTERNAL_BSP_INLINE_MODEL_LAST = "
            f"{external_replay.get('lastInlineModel', 0)}"
        ),
        (
            "BSP_EXTERNAL_BSP_SOURCE_MODEL_COUNT = "
            f"{external_models.get('usedModelCount', 0)}"
        ),
        (
            "BSP_EXTERNAL_BSP_SOURCE_FACE_COUNT = "
            f"{external_models.get('sourceFaceCount', 0)}"
        ),
        f"BSP_EXTERNAL_BSP_FLY_STATIC_COUNT = {external['flyStaticCount']}",
        f"BSP_EXTERNAL_BSP_FLY_EXTRA_SLOT_COUNT = {external['flyExtraSlotCount']}",
        f"BSP_EXTERNAL_BSP_ACTIVE_ROW_BYTES = {external['activeRowBytes']}",
        f"BSP_BRUSH_RUNTIME_FIRST_BANK = ${runtime['firstBank']:02X}",
        f"BSP_BRUSH_RUNTIME_BANK_COUNT = {runtime['bankCount']}",
        f"BSP_BRUSH_MODEL_COUNT = {metadata['geometry']['modelCount']}",
        f"BSP_BRUSH_FACE_COUNT = {metadata['geometry']['faceCount']}",
        f"BSP_BRUSH_INDEX_COUNT = {metadata['geometry']['indexCount']}",
        (
            "BSP_BRUSH_LIGHTMAPPED_TEXCOORD_AXIS_SPAN_Q4_MAX = "
            f"{metadata['lightmaps']['maximumTexcoordAxisSpanQ4']}"
        ),
        (
            "BSP_BRUSH_VISUAL_STATE_COUNT = "
            f"{metadata['visualStates']['visualStateCount']}"
        ),
        (f"BSP_BRUSH_ENTITY_ID_MAX = {metadata['visualStates']['maximumEntityId']}"),
        (
            "BSP_BRUSH_INLINE_MODEL_MAX = "
            f"{metadata['visualStates']['maximumInlineModel']}"
        ),
        "BSP_BRUSH_DISABLED_VISUAL_STATE = 0",
        f"BSP_BRUSH_REPLAY_ROW_COUNT = {metadata['replay']['rowCount']}",
        f"BSP_BRUSH_ENTITY_SLOT_COUNT = {metadata['replay']['entitySlotCount']}",
        f"BSP_BRUSH_VARIANT_COUNT = {metadata['replay']['variantCount']}",
        (
            "BSP_BRUSH_STATIC_BASELINE_COUNT = "
            f"{metadata['visualStates']['staticBaselineCount']}"
        ),
        (
            "BSP_BRUSH_REPLAY_LINK_MAX = "
            f"{metadata['visualStates']['fragmentLinkBounds']['replayMaximumNonSolidLinks']}"
        ),
        (
            "BSP_BRUSH_STATIC_LINK_COUNT = "
            f"{metadata['visualStates']['fragmentLinkBounds']['staticBaselineNonSolidLinks']}"
        ),
        (f"BSP_BRUSH_FLY_LINK_MAX = {fly_link_max}"),
        (
            "BSP_BRUSH_REPLAY_LEAF_MARKER_MAX = "
            f"{metadata['visualStates']['fragmentLinkBounds']['replayMaximumLeafMarkers']}"
        ),
        (
            "BSP_BRUSH_STATIC_LEAF_MARKER_COUNT = "
            f"{metadata['visualStates']['fragmentLinkBounds']['staticBaselineLeafMarkers']}"
        ),
        (f"BSP_BRUSH_FLY_LEAF_MARKER_MAX = {fly_leaf_marker_max}"),
        (
            "BSP_BRUSH_REPLAY_GROUP_FRAGMENT_MAX = "
            f"{metadata['visualStates']['fragmentLinkBounds']['replayMaximumLeafGroupFragments']}"
        ),
        (
            "BSP_BRUSH_REPLAY_GROUP_PROJECTED_VERTEX_MAX = "
            f"{metadata['visualStates']['fragmentLinkBounds']['replayMaximumLeafGroupProjectedVertices']}"
        ),
        (f"BSP_BRUSH_FLY_GROUP_FRAGMENT_MAX = {fly_group_fragment_max}"),
        (
            "BSP_BRUSH_FLY_GROUP_PROJECTED_VERTEX_MAX = "
            f"{fly_group_projected_vertex_max}"
        ),
        f"BSP_BRUSH_TEXTURE_COUNT = {metadata['textures']['extraTextureCount']}",
        (
            "BSP_BRUSH_MASKED_TEXTURE_COUNT = "
            f"{metadata['textures']['maskedTextureCount']}"
        ),
        f"BSP_BRUSH_TEXTURE_FIRST_BANK = ${metadata['capacity']['firstBrushBank']:02X}",
        f"BSP_BRUSH_TEXTURE_BANK_COUNT = {metadata['textures']['packedBankCount']}",
        "",
    ]
    for section in runtime["sections"]:
        prefix = f"BSP_BRUSH_{section['name']}"
        lines.extend(
            [
                f"{prefix}_BANK = ${section['bank']:02X}",
                f"{prefix}_ADDRESS = ${section['address']:04X}",
                f"{prefix}_BYTES = {section['bytes']}",
                f"{prefix}_RECORD_BYTES = {section['recordBytes']}",
                f"{prefix}_COUNT = {section['recordCount']}",
            ]
        )
    lines.extend(
        [
            "",
            f"BSP_BRUSH_FRAGMENT_FIRST_BANK = ${fragments['firstBank']:02X}",
            f"BSP_BRUSH_FRAGMENT_BANK_COUNT = {fragments['bankCount']}",
            f"BSP_BRUSH_FRAGMENT_VARIANT_COUNT = {fragments['variantCount']}",
            f"BSP_BRUSH_FRAGMENT_BUCKET_COUNT = {fragments['bucketCount']}",
            f"BSP_BRUSH_FRAGMENT_COUNT = {fragments['fragmentCount']}",
            (f"BSP_BRUSH_FRAGMENT_VERTEX_COUNT = {fragments['vertexOccurrenceCount']}"),
            (f"BSP_BRUSH_LEAF_HEAD_COUNT = {fragments['leafDomain']['headCount']}"),
            (
                "BSP_BRUSH_FRAGMENT_BUCKET_LEAF_MAX = "
                f"{fragments['leafDomain']['maximumBucketLeaf']}"
            ),
            (
                "BSP_BRUSH_SOLID_FALLBACK_LEAF = "
                f"{fragments['leafDomain']['solidFallbackLeaf']}"
            ),
            (
                "BSP_BRUSH_FRAGMENT_VARIANT_RECORD_BYTES = "
                f"{fragments['variantRecordBytes']}"
            ),
            (
                "BSP_BRUSH_FRAGMENT_BUCKET_RECORD_BYTES = "
                f"{fragments['bucketRecordBytes']}"
            ),
            (f"BSP_BRUSH_FRAGMENT_RECORD_BYTES = {fragments['fragmentRecordBytes']}"),
            (
                "BSP_BRUSH_FRAGMENT_FACE_RECORD_BYTES = "
                f"{fragments['faceMaterialRecordBytes']}"
            ),
            (
                "BSP_BRUSH_FRAGMENT_VERTEX_RECORD_BYTES = "
                f"{fragments['vertexRecordBytes']}"
            ),
            (
                "BSP_BRUSH_FRAGMENT_VARIANTS_BANK = $"
                f"{roles['control']['variants']['bank']:02X}"
            ),
            (
                "BSP_BRUSH_FRAGMENT_VARIANTS_ADDRESS = $"
                f"{roles['control']['variants']['address']:04X}"
            ),
            (
                "BSP_BRUSH_FRAGMENT_FACES_BANK = $"
                f"{roles['control']['faces']['bank']:02X}"
            ),
            (
                "BSP_BRUSH_FRAGMENT_FACES_ADDRESS = $"
                f"{roles['control']['faces']['address']:04X}"
            ),
            (
                "BSP_BRUSH_FRAGMENT_BUCKETS_BANK = $"
                f"{roles['control']['buckets']['bank']:02X}"
            ),
            (
                "BSP_BRUSH_FRAGMENT_BUCKETS_ADDRESS = $"
                f"{roles['control']['buckets']['address']:04X}"
            ),
            (
                "BSP_BRUSH_FRAGMENT_DESCRIPTORS_FIRST_BANK = $"
                f"{roles['descriptors']['firstBank']:02X}"
            ),
            (
                "BSP_BRUSH_FRAGMENT_DESCRIPTOR_BANK_COUNT = "
                f"{roles['descriptors']['bankCount']}"
            ),
            (
                "BSP_BRUSH_FRAGMENT_VERTICES_FIRST_BANK = $"
                f"{roles['vertices']['firstBank']:02X}"
            ),
            (
                "BSP_BRUSH_FRAGMENT_VERTEX_BANK_COUNT = "
                f"{roles['vertices']['bankCount']}"
            ),
            (
                "BSP_BRUSH_SOLID_LEAF_COUNT = "
                f"{metadata['worldComposition']['solidLeafCount']}"
            ),
            (f"BSP_BRUSH_LEAF_COUNT = {metadata['worldComposition']['leafCount']}"),
            "",
        ]
    )
    return "\n".join(lines).encode("ascii")


def inline_entity_definitions(bsp: bytes) -> dict[int, dict[str, str]]:
    lumps = bsp_tools.lump_ranges(bsp)
    entities = bsp_tools.parse_entities(
        bsp_tools.lump_data(bsp, lumps, bsp_tools.LUMP_ENTITIES)
    )
    result: dict[int, dict[str, str]] = {}
    for entity in entities:
        model = entity.get("model", "")
        if not model.startswith("*") or not model[1:].isdigit():
            continue
        model_id = int(model[1:])
        if model_id <= 0 or model_id in result:
            raise ValueError(f"invalid or duplicate BSP inline model {model!r}")
        result[model_id] = entity
    return result


def _state_summary(
    entity: int,
    states: list[tuple[int, BrushEntityState]],
    definitions: dict[int, dict[str, str]],
) -> dict[str, Any]:
    model_ids = sorted({state.inline_model for _row, state in states})
    if len(model_ids) != 1:
        raise ValueError(f"entity {entity} changes inline model in the replay")
    model_id = model_ids[0]
    definition = definitions.get(model_id, {})
    origins = sorted({state.origin for _row, state in states})
    frames = sorted({state.frame for _row, state in states})
    angles = sorted({state.angles for _row, state in states})
    return {
        "entity": entity,
        "inlineModel": model_id,
        "classname": definition.get("classname", ""),
        "firstRow": states[0][0],
        "lastRow": states[-1][0],
        "activeRowCount": len(states),
        "originStateCount": len(origins),
        "originMinimum": [min(origin[axis] for origin in origins) for axis in range(3)],
        "originMaximum": [max(origin[axis] for origin in origins) for axis in range(3)],
        "frames": frames,
        "angles": [list(angle) for angle in angles],
    }


def replay_audit(
    replay: CanonicalBrushReplay,
    definitions: dict[int, dict[str, str]],
) -> dict[str, Any]:
    observations: dict[int, list[tuple[int, BrushEntityState]]] = defaultdict(list)
    for row in replay.rows:
        for state in row.brushes:
            observations[state.entity_number].append((row.index, state))
    entities = [
        _state_summary(entity, states, definitions)
        for entity, states in sorted(observations.items())
    ]
    translating = [entry for entry in entities if entry["originStateCount"] > 1]
    frame_changing = [entry for entry in entities if len(entry["frames"]) > 1]
    angled = [
        entry
        for entry in entities
        if any(angle != [0.0, 0.0, 0.0] for angle in entry["angles"])
    ]
    class_counts: dict[str, int] = {classname: 0 for classname in MOVING_BRUSH_CLASSES}
    for entry in translating:
        classname = entry["classname"]
        class_counts[classname] = class_counts.get(classname, 0) + 1
    signon_models = {state.inline_model for state in replay.signon_brushes}
    return {
        "signon": {
            "brushEntityCount": len(replay.signon_brushes),
            "inlineModelCount": len(signon_models),
        },
        "everActive": {
            "brushEntityCount": len(entities),
            "inlineModelCount": len({entry["inlineModel"] for entry in entities}),
            "entities": entities,
        },
        "perRow": {
            "minimumActive": min(len(row.brushes) for row in replay.rows),
            "maximumActive": max(len(row.brushes) for row in replay.rows),
            "totalActiveStates": sum(len(row.brushes) for row in replay.rows),
        },
        "translating": {
            "entityCount": len(translating),
            "byClass": dict(sorted(class_counts.items())),
            "entities": translating,
        },
        "frameChanging": {
            "entityCount": len(frame_changing),
            "entities": frame_changing,
        },
        "nonzeroAngle": {
            "entityCount": len(angled),
            "entities": angled,
        },
    }


def compact_runtime_blockers(replay: CanonicalBrushReplay) -> tuple[str, ...]:
    """Name replay properties that the current runtime cannot represent."""

    authority = {state.entity_number for state in replay.signon_brushes} | {
        state.entity_number for row in replay.rows for state in row.brushes
    }
    blockers: list[str] = []
    if any(not 0 < entity <= 0xFFFF for entity in authority):
        blockers.append("rawAuthorityUint16")
    if any(state.angles != (0.0, 0.0, 0.0) for state in replay.signon_brushes) or any(
        state.angles != (0.0, 0.0, 0.0) for row in replay.rows for state in row.brushes
    ):
        blockers.append("translationOnly")
    states_by_entity: dict[int, set[BrushEntityState]] = defaultdict(set)
    for row in replay.rows:
        for state in row.brushes:
            states_by_entity[state.entity_number].add(state)
    if any(len(states) > 0xFF for states in states_by_entity.values()):
        blockers.append("perEntityVariantUint8")
    replayed_entities = set(states_by_entity)
    signon_only = {
        state.entity_number
        for state in replay.signon_brushes
        if state.entity_number not in replayed_entities
    }
    if len(replayed_entities) + len(signon_only) > 128:
        blockers.append("runtimeSlot128")
    if sum(map(len, states_by_entity.values())) > 0xFFFF:
        blockers.append("globalVariantUint16")
    if any(
        not 0 < state.inline_model <= 0xFF for state in replay.signon_brushes
    ) or any(
        not 0 < state.inline_model <= 0xFF
        for row in replay.rows
        for state in row.brushes
    ):
        blockers.append("inlineModelUint8")
    return tuple(blockers)


def static_playback_fallback(replay: CanonicalBrushReplay) -> CanonicalBrushReplay:
    """Retain safe baseline geometry while disabling unsupported motion."""

    signon = tuple(
        state
        for state in replay.signon_brushes
        if 0 < state.entity_number <= 0xFFFF
        and 0 < state.inline_model <= 0xFF
        and state.angles == (0.0, 0.0, 0.0)
    )
    return replace(
        replay,
        signon_brushes=signon,
        rows=tuple(replace(row, brushes=()) for row in replay.rows),
    )


def resolve_configured_profile(
    profile_root: Path,
    configured_value: object,
    *,
    field: str,
) -> tuple[Path, str]:
    """Resolve a config-owned profile without publishing a host-local path."""

    configured_path = Path(str(configured_value))
    if configured_path.anchor:
        raise ValueError(f"externalBsp.{field} must be a relative path")
    portable_path = configured_path.as_posix()
    return profile_root / configured_path, portable_path


def build_outputs(
    pak_path: Path,
    demo_path: Path | None = None,
    *,
    config_path: Path | None = None,
) -> tuple[dict[Path, bytes], dict[str, Any]]:
    if demo_path is not None and config_path is not None:
        raise ValueError("demo_path and config_path are mutually exclusive")
    archive = bsp_tools.PakArchive(pak_path)
    config_document = (
        json.loads(config_path.read_text(encoding="utf-8"))
        if config_path is not None
        else {}
    )
    if config_path is not None:
        selected_demo = resolve_configured_demo(archive.read, config_path)
        sample_rate_hz = configured_playback_sample_rate(config_path)
    elif demo_path is not None:
        selected_demo = resolve_demo_source(
            DemoSource("file", str(demo_path.resolve()), DEFAULT_CONFIG),
            archive.read,
        )
        sample_rate_hz = DEFAULT_PLAYBACK_SAMPLE_RATE_HZ
    else:
        selected_demo = resolve_demo_source(
            DemoSource("pak", bsp_tools.DEMO_ENTRY, DEFAULT_CONFIG), archive.read
        )
        sample_rate_hz = DEFAULT_PLAYBACK_SAMPLE_RATE_HZ
    demo = selected_demo.payload
    map_entry = selected_demo.map_entry
    bsp = archive.read(map_entry)
    palette = archive.read(bsp_tools.PALETTE_ENTRY)
    replay = extract_canonical_brush_replay(demo, map_entry, sample_rate_hz)
    payload = encode_brush_replay(replay)
    precise_camera_track = encode_precise_camera_track(replay.rows)
    camera_track_fingerprint = fnv1a64(precise_camera_track)
    if camera_track_fingerprint != replay.camera_track_fnv1a64:
        raise AssertionError("canonical camera fingerprint is inconsistent")
    decoded = decode_brush_replay(payload)
    expected_rows = tuple(row.brushes for row in replay.rows)
    if decoded.rows != expected_rows:
        raise AssertionError("brush replay codec does not round-trip losslessly")
    steps = step_row_indices(len(replay.rows), replay.sample_rate_hz)
    audit = replay_audit(replay, inline_entity_definitions(bsp))
    metadata: dict[str, Any] = {
        "schema": "quake-bsp-brush-replay",
        "version": BRUSH_REPLAY_VERSION,
        "source": {
            "pakPathHint": bsp_tools.QUAKE_PAK_PATH_HINT,
            "mapEntry": map_entry,
            "demoEntry": selected_demo.label,
            "demoSource": selected_demo.source.kind,
            "demoLocator": selected_demo.source.locator,
            "bspSha256": hashlib.sha256(bsp).hexdigest(),
            "demoSha256": selected_demo.sha256,
        },
        "timeline": {
            "contract": "newest source camera and entity snapshot due; no interpolation",
            "sampleRateHz": replay.sample_rate_hz,
            "firstSourceServerTime": replay.first_server_time,
            "textureAnimationClock": (
                "firstSourceServerTime + rowIndex / sampleRateHz"
            ),
            "cameraTrackFnv1a64": f"{camera_track_fingerprint:016x}",
            "cameraTrackSha256": hashlib.sha256(precise_camera_track).hexdigest(),
            "sourceCameraSamples": replay.source_sample_count,
            "rowCount": len(replay.rows),
            "firstRow": replay.rows[0].index,
            "lastRow": replay.rows[-1].index,
            "stepSampleRateHz": BRUSH_REPLAY_STEP_RATE_HZ,
            "orderedPoseStride": (replay.sample_rate_hz // BRUSH_REPLAY_STEP_RATE_HZ),
            "stepRowCount": len(steps),
            "stepFirstRow": steps[0],
            "stepLastRow": steps[-1],
        },
        "format": {
            "magic": "QBR2",
            "headerBytes": BRUSH_REPLAY_HEADER.size,
            "snapshotDirectoryRecordBytes": BRUSH_REPLAY_SNAPSHOT.size,
            "entityStateBytes": BRUSH_REPLAY_STATE.size,
            "activeStateEncoding": "full active set per deduplicated snapshot",
            "coordinateEncoding": "signed Q3",
            "angleEncoding": "protocol signed byte",
        },
        "audit": audit,
        "output": {
            "path": STREAM_NAME.as_posix(),
            "bytes": len(payload),
            "sha256": hashlib.sha256(payload).hexdigest(),
            "uniqueSnapshotCount": len({row.brushes for row in replay.rows}),
        },
    }
    rendered_metadata = (json.dumps(metadata, indent=2, sort_keys=True) + "\n").encode(
        "ascii"
    )
    external_replay = extract_canonical_external_bsp_replay(
        demo, map_entry, sample_rate_hz
    )
    external_payload = encode_external_bsp_replay(external_replay)
    canonical_active_rows, external_active_metadata = encode_external_active_rows(
        external_replay
    )
    external_config = config_document.get("externalBsp", {})
    external_enabled = bool(external_config.get("enabled", True))
    profile_root = config_path.parent if config_path is not None else TOOLS_DIR.parent
    visibility_profile, visibility_profile_hint = resolve_configured_profile(
        profile_root,
        external_config.get(
            "visibilityProfile", "profiles/external-bsp-visibility.json"
        ),
        field="visibilityProfile",
    )
    direct_profile, direct_profile_hint = resolve_configured_profile(
        profile_root,
        external_config.get("directSafetyProfile", "profiles/brush-direct-safety.json"),
        field="directSafetyProfile",
    )
    if external_enabled:
        external_active_rows = canonical_active_rows
        external_active_entities = tuple(external_active_metadata["entityIds"])
        external_models = {
            name: archive.read(name) for name in external_replay.model_names
        }
        visible_external_faces, visibility_metadata = load_external_visibility_profile(
            visibility_profile,
            bsp=bsp,
            qer1=external_payload,
            qbr2=payload,
            pak_sha256=hashlib.sha256(pak_path.read_bytes()).hexdigest(),
            external=external_replay,
        )
        bound_direct_inputs = {
            name: hashlib.sha256(
                (DEFAULT_OUTPUT / filename).read_bytes()
            ).hexdigest()
            for name, filename in {
                "metadata": "QuakeBSPMetadata.json",
                "demoTrack": "QuakeBSPDemoTrack.bin",
                "demoTiming": "QuakeBSPDemoTiming.bin",
                "orderedCameraTrack": "QuakeBSPDemoPrecise.bin",
                "orderedTiming": "QuakeBSPDemoPreciseTiming.bin",
            }.items()
        }
        direct_safe_mask, direct_safety_metadata = load_brush_direct_safety_profile(
            direct_profile,
            row_count=len(external_replay.rows),
            visibility_sha256=visibility_metadata["sha256"],
            bound_inputs=bound_direct_inputs,
        )
        visibility_metadata["path"] = visibility_profile_hint
        direct_safety_metadata["path"] = direct_profile_hint
        prepared_source, combined_replay = prepare_brush_source(
            bsp,
            replay,
            external_replay=external_replay,
            external_model_payloads=external_models,
            visible_external_faces_by_row=visible_external_faces,
        )
    else:
        external_active_rows = b""
        external_active_entities = ()
        direct_safe_mask = b""
        visibility_metadata = {"enabled": False}
        direct_safety_metadata = {"enabled": False}
        prepared_source, combined_replay = prepare_brush_source(bsp, replay)
    visible_replay, admission = derive_demo_visible_replay(
        bsp,
        combined_replay,
        prepared_source=prepared_source,
    )
    blockers = compact_runtime_blockers(visible_replay)
    if map_entry != bsp_tools.BSP_ENTRY:
        blockers = (*blockers, "alternateMapStaticBrushes")
    runtime_replay = (
        static_playback_fallback(visible_replay) if blockers else visible_replay
    )
    assets = build_brush_assets(
        bsp,
        palette,
        runtime_replay,
        prepared_source=prepared_source,
        direct_safe_mask=direct_safe_mask,
        external_active_rows=external_active_rows,
        external_active_entities=external_active_entities,
    )
    asset_metadata = {
        **assets.metadata,
        "runtimeReplay": {
            "supported": not blockers,
            "mode": (
                "demo-visible-derived" if not blockers else "static-baseline-fallback"
            ),
            "blockers": list(blockers),
            "canonicalRowCount": len(replay.rows),
            "runtimeRowCount": len(runtime_replay.rows),
            "admission": admission,
            "fallbackSignonModelCount": len(runtime_replay.signon_brushes),
            "behavior": (
                (
                    "camera-bound exact visible playback from translated poses "
                    "split through the static world BSP"
                )
                if not blockers
                else (
                    "SNES playback remains available with dynamic brushes "
                    "forced off; safe baseline geometry remains packaged"
                )
            ),
        },
        "source": {
            **assets.metadata["source"],
            "pakPathHint": bsp_tools.QUAKE_PAK_PATH_HINT,
            "mapEntry": map_entry,
            "demoEntry": selected_demo.label,
            "demoSource": selected_demo.source.kind,
            "demoLocator": selected_demo.source.locator,
            "demoSha256": selected_demo.sha256,
        },
        "canonicalSourceReplay": {
            "path": STREAM_NAME.as_posix(),
            "bytes": len(payload),
            "sha256": hashlib.sha256(payload).hexdigest(),
        },
    }
    external_metadata = asset_metadata["source"].setdefault("externalBsp", {})
    external_metadata["configuration"] = {
        "enabled": external_enabled,
        "visibilityProfile": visibility_profile_hint,
        "directSafetyProfile": direct_profile_hint,
    }
    external_metadata["qer1"] = {
        "bytes": len(external_payload),
        "sha256": hashlib.sha256(external_payload).hexdigest(),
        "cameraTrackFnv1a64": f"{external_replay.camera_track_fnv1a64:016x}",
        "rowCount": len(external_replay.rows),
    }
    external_metadata["visibility"] = visibility_metadata
    external_metadata["directSafety"] = direct_safety_metadata
    external_metadata["activeRows"] = {
        **external_active_metadata,
        "packaged": external_enabled,
    }
    include_payload = asset_include(asset_metadata)
    asset_metadata["outputs"][ASSET_INCLUDE_NAME.as_posix()] = {
        "bytes": len(include_payload),
        "sha256": hashlib.sha256(include_payload).hexdigest(),
    }
    rendered_asset_metadata = (
        json.dumps(asset_metadata, indent=2, sort_keys=True) + "\n"
    ).encode("ascii")
    return {
        STREAM_NAME: payload,
        METADATA_NAME: rendered_metadata,
        ASSET_METADATA_NAME: rendered_asset_metadata,
        ASSET_INCLUDE_NAME: include_payload,
        **assets.outputs,
    }, metadata


def write_or_check(outputs: dict[Path, bytes], output: Path, check: bool) -> None:
    try:
        sync_generated_outputs(
            outputs,
            output,
            check=check,
            owned_families=OWNED_OUTPUTS,
        )
    except GeneratedOutputError as error:
        raise SystemExit(f"generated Quake brush replay is stale:\n{error}") from None


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--pak", type=Path)
    parser.add_argument("--config", type=Path, default=DEFAULT_CONFIG)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    started = time.perf_counter()
    args = parse_args(argv)
    outputs, metadata = build_outputs(
        bsp_tools.locate_quake_pak(args.pak), config_path=args.config
    )
    write_or_check(outputs, args.output, args.check)
    audit = metadata["audit"]
    action = "verified" if args.check else "generated"
    print(
        f"{action} {metadata['timeline']['rowCount']} aligned brush rows; "
        f"{audit['everActive']['brushEntityCount']} entities ever active, "
        f"{audit['translating']['entityCount']} translate, "
        f"{audit['frameChanging']['entityCount']} change frame; "
        f"packed {audit['signon']['brushEntityCount']} signon models; "
        f"elapsed={time.perf_counter() - started:.3f}s"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
