#!/usr/bin/env python3
# ruff: noqa: E402
"""Generate compact ROM-facing Quake sky markers, phases, and constants."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

from workspace_paths import shared_tools_root, workspace_root
import sys
import time
from typing import Any, Mapping, Sequence


TOOLS = Path(__file__).resolve().parent
EXAMPLE = workspace_root(__file__) / "src/snes_quake"
SHARED = shared_tools_root(__file__)
sys.path[:0] = [str(TOOLS), str(SHARED)]

import audit_quake_bsp_sky_assets as asset_audit  # noqa: E402
from snes_tooling.shared.generated_outputs import (
    GeneratedOutputError,
    sync_generated_outputs,
)  # noqa: E402
import quake_bsp_sky_assets as sky  # noqa: E402
from quake_rom_config import DEFAULT_CONFIG, configured_sky  # noqa: E402


DEFAULT_DATA = EXAMPLE / "Data"
DEFAULT_CORPUS = workspace_root(__file__) / "config/profiles/QuakeBSPSkyEndpointCorpus.json"
PHASE_PATH = Path("QuakeBSPSkyPhases.bin")
CONSTANTS_PATH = Path("QuakeBSPSkyAssets.i")
ASSEMBLY_PATH = Path("QuakeBSPSkyAssets.s")
METADATA_PATH = Path("QuakeBSPSkyAssets.json")
TIMING_PATH = Path("QuakeBSPDemoPreciseTiming.bin")
PHASE_GSU_ROM_BANK = 0x03
PHASE_CPU_ROM_BANK = 0x83
PHASE_BANK_ADDRESS = 0x8000
PHASE_BANK_BYTES = 0x8000
MARKER_HASH_SHIFT = 5
MARKER_LUT_BYTES = 16
MAX_MARKER_LUT_BYTES = 256
MAX_SKY_FACE_MARKERS = asset_audit.MAX_SKY_FACE_MARKERS


class GenerationError(RuntimeError):
    """Raised when audited sources cannot satisfy the generated ABI."""


def _require(condition: bool, message: str) -> None:
    if not condition:
        raise GenerationError(message)


def _sha256(payload: bytes) -> str:
    return hashlib.sha256(payload).hexdigest()


def marker_hash_layout(
    assignments: Sequence[Mapping[str, int]],
) -> tuple[int, int]:
    """Choose the smallest deterministic collision-free face hash layout."""

    faces = tuple(int(record["face"]) for record in assignments)
    _require(faces, "sky marker table must not be empty")
    _require(len(set(faces)) == len(faces), "sky marker faces are not unique")
    _require(
        len(faces) <= MAX_MARKER_LUT_BYTES,
        "sky marker table exceeds the face hash capacity",
    )
    shifts = (MARKER_HASH_SHIFT, *range(1, MARKER_HASH_SHIFT), *range(6, 16))
    lut_bytes = MARKER_LUT_BYTES
    while lut_bytes <= MAX_MARKER_LUT_BYTES:
        mask = lut_bytes - 1
        for shift in shifts:
            slots = tuple((face ^ (face >> shift)) & mask for face in faces)
            if len(set(slots)) == len(slots):
                return shift, lut_bytes
        lut_bytes *= 2
    raise GenerationError("configured sky faces have no collision-free marker hash")


def marker_lut(
    assignments: Sequence[Mapping[str, int]],
    *,
    hash_shift: int | None = None,
    lut_bytes: int | None = None,
) -> bytes:
    """Build the collision-free marker hash for the configured map."""

    if hash_shift is None or lut_bytes is None:
        _require(
            hash_shift is None and lut_bytes is None,
            "sky marker hash layout must be specified together",
        )
        hash_shift, lut_bytes = marker_hash_layout(assignments)
    _require(
        lut_bytes >= MARKER_LUT_BYTES
        and lut_bytes <= MAX_MARKER_LUT_BYTES
        and not (lut_bytes & (lut_bytes - 1)),
        "sky marker LUT size is not a supported power of two",
    )

    table = bytearray(lut_bytes)
    occupied: set[int] = set()
    markers: set[int] = set()
    for record in assignments:
        face = int(record["face"])
        marker = int(record["marker"])
        slot = (face ^ (face >> hash_shift)) & (lut_bytes - 1)
        _require(0 < marker <= 0xFF, "canonical sky marker is not an opaque byte")
        _require(slot not in occupied, "canonical sky marker hash collided")
        occupied.add(slot)
        markers.add(marker)
        table[slot] = marker
    _require(occupied, "sky marker table must not be empty")
    _require(
        len(markers) <= MAX_SKY_FACE_MARKERS,
        "sky marker palette exceeds the runtime marker capacity",
    )
    return bytes(table)


def _hex(value: int, width: int) -> str:
    return f"${value:0{width}X}"


def constants_text(
    report: Mapping[str, Any],
    phases: bytes,
    lut: bytes,
    phase_address: int,
    *,
    enabled: bool = True,
    marker_hash_shift: int = MARKER_HASH_SHIFT,
) -> bytes:
    assignments = report["faceMarkers"]["assignments"]
    gate = report["arithmeticGate"]
    bounds = gate["bounds"]
    sum_squares = int(bounds["maximumSumSquares"])
    phase_end = phase_address + len(phases)
    lines = [
        "; Generated by generate_quake_bsp_sky_assets.py; do not edit.",
        ".ifndef __QUAKE_BSP_SKY_ASSETS_I__",
        "__QUAKE_BSP_SKY_ASSETS_I__ = 1",
        "",
        f"BSP_SKY_ENABLED = {int(enabled)}",
        f"BSP_WORLD_SKY_TEXTURE_ID = {report['skyTexture']['packedTextureId'] if enabled else 0xFF}",
        f"BSP_WORLD_SKY_FACE_COUNT = {len(assignments)}",
    ]
    _require(
        len({int(record["marker"]) for record in assignments}) <= MAX_SKY_FACE_MARKERS,
        "sky marker palette exceeds the runtime marker capacity",
    )
    for ordinal in range(MAX_SKY_FACE_MARKERS):
        if ordinal < len(assignments):
            record = assignments[ordinal]
            face = int(record["face"])
            marker = int(record["marker"])
            slot = (face ^ (face >> marker_hash_shift)) & (len(lut) - 1)
        else:
            face = -1
            marker = 0x100
            slot = -1
        lines.extend(
            (
                f"BSP_WORLD_SKY_FACE_{ordinal} = {face}",
                f"BSP_WORLD_SKY_MARKER_{ordinal} = {marker}",
                f"BSP_WORLD_SKY_MARKER_SLOT_{ordinal} = {slot}",
            )
        )
    lines.extend(
        (
            f"BSP_SKY_MARKER_HASH_SHIFT = {marker_hash_shift}",
            f"BSP_SKY_MARKER_LUT_BYTES = {len(lut)}",
            f"BSP_SKY_SAFE_MARKER_COUNT = {report['faceMarkers']['safeIndexCount']}",
            "",
            f"BSP_SKY_SOURCE_WIDTH = {sky.SKY_SOURCE_WIDTH}",
            f"BSP_SKY_SOURCE_HEIGHT = {sky.SKY_SOURCE_HEIGHT}",
            f"BSP_SKY_LAYER_SIZE = {sky.SKY_LAYER_SIZE}",
            f"BSP_SKY_PROJECTION_SCALE = {sky.SKY_PROJECTION_SCALE}",
            f"BSP_SKY_SPAN_MAXIMUM = {sky.SKY_SPAN_MAXIMUM}",
            f"BSP_SKY_COORD_FRACTION_BITS = {sky.SKY_FIXED_FRACTION_BITS}",
            f"BSP_SKY_COORD_MASK = {_hex(sky.SKY_FIXED_MASK, 6)}",
            f"BSP_SKY_PHASE_MASK = {_hex((1 << 23) - 1, 6)}",
            f"BSP_SKY_PHASE_RECORD_BYTES = {sky.SKY_PHASE_RECORD_BYTES}",
            f"BSP_SKY_PHASE_POSE_COUNT = {len(phases) // sky.SKY_PHASE_RECORD_BYTES}",
            f"BSP_SKY_PHASE_BYTES = {len(phases)}",
            f"BSP_SKY_PHASE_GSU_ROM_BANK = {_hex(PHASE_GSU_ROM_BANK, 2)}",
            f"BSP_SKY_PHASE_GSU_ROM_ADDRESS = {_hex(phase_address, 4)}",
            f"BSP_SKY_PHASE_GSU_ROM_END_ADDRESS = {_hex(phase_end, 4)}",
            f"BSP_SKY_PHASE_CPU_ROM_ADDRESS = {_hex((PHASE_CPU_ROM_BANK << 16) | phase_address, 6)}",
            "BSP_SKY_FLY_PHASE_Q16 = 0",
            f"BSP_SKY_FLY_CLOCK_FRACTION_BITS = {sky.FLY_CLOCK_FRACTION_BITS}",
            f"BSP_SKY_FLY_CLOCK_PHASE_STEP_Q16 = {sky.FLY_CLOCK_PHASE_STEP_Q16}",
            f"BSP_SKY_FLY_CLOCK_FRACTION_STEP_Q8 = {sky.FLY_CLOCK_FRACTION_STEP_Q8}",
            "",
            "BSP_SKY_RAY_COMPONENT_DENOMINATOR = 64",
            "BSP_SKY_RAY_PRESERVE_EXACT_NUMERATORS = 1",
            f"BSP_SKY_RAY_NX_MIN = {bounds['componentMinimums'][0]}",
            f"BSP_SKY_RAY_NX_MAX = {bounds['componentMaximums'][0]}",
            f"BSP_SKY_RAY_NY_MIN = {bounds['componentMinimums'][1]}",
            f"BSP_SKY_RAY_NY_MAX = {bounds['componentMaximums'][1]}",
            f"BSP_SKY_RAY_NZ_MIN = {bounds['componentMinimums'][2]}",
            f"BSP_SKY_RAY_NZ_MAX = {bounds['componentMaximums'][2]}",
            f"BSP_SKY_RAY_SUMSQ_BITS = {bounds['sumSquaresBits']}",
            f"BSP_SKY_RAY_SUMSQ_MAX_LO = {_hex(sum_squares & 0xFFFF, 4)}",
            f"BSP_SKY_RAY_SUMSQ_MAX_MID = {_hex((sum_squares >> 16) & 0xFFFF, 4)}",
            f"BSP_SKY_RAY_SUMSQ_MAX_HI = {_hex((sum_squares >> 32) & 0xFFFF, 4)}",
            f"BSP_SKY_MAGNITUDE_MIN = {bounds['minimumFloorMagnitude']}",
            f"BSP_SKY_FLOOR_MAGNITUDE_MAX = {bounds['maximumFloorMagnitude']}",
            f"BSP_SKY_MAGNITUDE_MAX = {bounds['maximumRoundedMagnitude']}",
            f"BSP_SKY_MAGNITUDE_BITS = {bounds['roundedMagnitudeBits']}",
            "BSP_SKY_MAGNITUDE_ROUND_NUMERATOR = 3",
            "BSP_SKY_MAGNITUDE_ROUND_DENOMINATOR = 4",
            "BSP_SKY_MAGNITUDE_ROUND_TIE_UP = 1",
            f"BSP_SKY_MAGNITUDE_REMAINDER_MAX = {bounds['maximumFloorRemainder']}",
            f"BSP_SKY_MAGNITUDE_REMAINDER_BITS = {bounds['floorRemainderBits']}",
            f"BSP_SKY_MAGNITUDE_ROUND_THRESHOLD_MAX = {bounds['maximumRoundingThreshold']}",
            f"BSP_SKY_MAGNITUDE_ROUND_THRESHOLD_BITS = {bounds['roundingThresholdBits']}",
            f"BSP_SKY_ACCEPTED_ENDPOINT_MAX_DELTA_Q16 = {gate['acceptedThreeQuarter']['maximumRawEndpointDeltaQ16']}",
            f"BSP_SKY_EXACT_ENDPOINT_MAX_DELTA_Q16 = {gate['acceptedThreeQuarter']['maximumRawEndpointDeltaQ16']}",
            "BSP_SKY_RECIPROCAL_FRACTION_BITS = 17",
            "BSP_SKY_RECIPROCAL_MAGNITUDE_BITS = 20",
            "BSP_SKY_RECIPROCAL_NUMERATOR_SHIFT = 37",
            "BSP_SKY_RECIPROCAL_RESULT_SHIFT = 21",
            "BSP_SKY_RECIPROCAL_MIN = 175835",
            "BSP_SKY_RECIPROCAL_MAX = 226039",
            "",
            ".macro BSP_SKY_EMIT_FACE_MARKER_LUT",
            *(
                "        .byte "
                + ", ".join(_hex(value, 2) for value in lut[offset : offset + 8])
                for offset in range(0, len(lut), 8)
            ),
            ".endmacro",
            "",
            ".endif",
            "",
        )
    )
    return "\n".join(lines).encode("ascii")


def assembly_text(phases: bytes, phase_address: int) -> bytes:
    phase_end = phase_address + len(phases)
    return (
        "; Generated by generate_quake_bsp_sky_assets.py; do not edit.\n"
        '.segment "BSP_DEMO_TIMING"\n'
        "QuakeBSPSkyPhases:\n"
        '        .incbin "Data/QuakeBSPSkyPhases.bin"\n'
        "QuakeBSPSkyPhasesEnd:\n"
        '.assert QuakeBSPSkyPhases = QuakeBSPDemoPreciseTimingEnd, error, "Sky phases must immediately follow precise timing"\n'
        '.assert QuakeBSPSkyPhasesEnd - QuakeBSPSkyPhases = BSP_SKY_PHASE_BYTES, error, "Sky phase asset size disagrees"\n'
        f'.assert QuakeBSPSkyPhases = {_hex((PHASE_CPU_ROM_BANK << 16) | phase_address, 6)}, lderror, "Sky phase asset moved"\n'
        f'.assert QuakeBSPSkyPhasesEnd = {_hex((PHASE_CPU_ROM_BANK << 16) | phase_end, 6)}, lderror, "Sky phase asset end moved"\n'
        '.assert QuakeBSPSkyPhasesEnd-QuakeBSPDemoPreciseTiming = BSP_DEMO_PRECISE_TIMING_BYTES+BSP_SKY_PHASE_BYTES, lderror, "Timing/sky prefix size disagrees"\n'
    ).encode("ascii")


def outputs_for(
    data_dir: Path,
    endpoint_corpus: Path,
    *,
    enabled: bool = True,
) -> dict[Path, bytes]:
    try:
        audit = asset_audit.build_configured_report(
            data_dir, endpoint_corpus, markers_enabled=enabled
        )
    except asset_audit.AuditError as error:
        raise GenerationError(
            "configured map cannot satisfy the sky marker contract"
        ) from error
    _require(
        audit["arithmeticGate"]["status"] == "passed",
        "sky arithmetic gate did not pass",
    )
    phase = audit["phaseAssetProposal"]
    phases = sky.build_demo_phase_asset(
        float(phase["firstServerTime"]),
        int(phase["sourcePoseCount"]),
        int(phase["sourceRateHz"]),
    )
    _require(_sha256(phases) == phase["candidateSha256"], "audited sky phases changed")
    timing = (data_dir / TIMING_PATH).read_bytes()
    phase_address = PHASE_BANK_ADDRESS + len(timing)
    _require(
        phase_address >= PHASE_BANK_ADDRESS,
        "precise timing begins before the sky phase bank",
    )
    _require(
        phase_address + len(phases) <= PHASE_BANK_ADDRESS + PHASE_BANK_BYTES,
        "sky phase asset crosses GSU ROM bank $03",
    )
    assignments = audit["faceMarkers"]["assignments"] if enabled else []
    if enabled:
        hash_shift, lut_bytes = marker_hash_layout(assignments)
        lut = marker_lut(assignments, hash_shift=hash_shift, lut_bytes=lut_bytes)
    else:
        hash_shift = MARKER_HASH_SHIFT
        lut = bytes(MARKER_LUT_BYTES)
    constants = constants_text(
        audit,
        phases,
        lut,
        phase_address,
        enabled=enabled,
        marker_hash_shift=hash_shift,
    )
    assembly = assembly_text(phases, phase_address)
    metadata = {
        "schema": "quake-bsp-snes-sky-assets-v1",
        "status": "generated",
        "enabled": enabled,
        "texture": audit["skyTexture"],
        "faceMarkers": {
            **audit["faceMarkers"],
            "assignments": assignments,
            "runtimeMarkerCount": len({item["marker"] for item in assignments}),
            "hashShift": hash_shift,
            "lutBytes": len(lut),
            "lutHex": lut.hex(),
        },
        "phase": {
            "encoding": phase["encoding"],
            "recordBytes": phase["recordBytes"],
            "sourcePoseCount": phase["sourcePoseCount"],
            "bytes": len(phases),
            "sha256": _sha256(phases),
            "gsuRomBank": PHASE_GSU_ROM_BANK,
            "gsuRomAddress": phase_address,
            "gsuRomEndAddress": phase_address + len(phases),
            "flySurfaceTime": 0.0,
            "flyPhaseQ16": 0,
            "flyClock": {
                "source": "unpaused NTSC VBlank phase oracle",
                "claimsExactServerTime": False,
                "videoHz": sky.SNES_NTSC_FRAMES_PER_SECOND,
                "fractionBits": sky.FLY_CLOCK_FRACTION_BITS,
                "phaseStepQ16": sky.FLY_CLOCK_PHASE_STEP_Q16,
                "fractionStepQ8": sky.FLY_CLOCK_FRACTION_STEP_Q8,
                "effectiveTexelsPerSecond": (
                    sky.FLY_CLOCK_STEP_Q24
                    * sky.SNES_NTSC_FRAMES_PER_SECOND
                    / (
                        sky.FLY_CLOCK_FRACTION_DENOMINATOR
                        * (1 << sky.SKY_FIXED_FRACTION_BITS)
                    )
                ),
            },
            "timingInput": {
                "path": TIMING_PATH.name,
                "bytes": len(timing),
                "sha256": _sha256(timing),
            },
        },
        "arithmeticGate": audit["arithmeticGate"],
        "demoVariant": audit.get("demoVariant", {"enabled": False}),
        "resourceImpact": {
            "phaseBytes": len(phases),
            "duplicateTextureBytes": 0,
            "textureDirectoryByteDelta": 0,
            "markerLutBytes": len(lut),
        },
        "outputs": {
            PHASE_PATH.name: {"bytes": len(phases), "sha256": _sha256(phases)},
            CONSTANTS_PATH.name: {
                "bytes": len(constants),
                "sha256": _sha256(constants),
            },
            ASSEMBLY_PATH.name: {"bytes": len(assembly), "sha256": _sha256(assembly)},
        },
        "inputs": audit["inputs"],
    }
    metadata_bytes = (json.dumps(metadata, indent=2, sort_keys=True) + "\n").encode(
        "ascii"
    )
    return {
        PHASE_PATH: phases,
        CONSTANTS_PATH: constants,
        ASSEMBLY_PATH: assembly,
        METADATA_PATH: metadata_bytes,
    }


def parse_args(argv: Sequence[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--data-dir", type=Path, default=DEFAULT_DATA)
    parser.add_argument("--endpoint-corpus", type=Path, default=DEFAULT_CORPUS)
    parser.add_argument("--output", type=Path, default=DEFAULT_DATA)
    parser.add_argument("--config", type=Path, default=DEFAULT_CONFIG)
    parser.add_argument("--check", action="store_true")
    return parser.parse_args(argv)


def main(argv: Sequence[str] | None = None) -> int:
    started = time.perf_counter()
    args = parse_args(argv)
    try:
        enabled = configured_sky(args.config.resolve()).enabled
        outputs = outputs_for(
            args.data_dir.resolve(), args.endpoint_corpus.resolve(), enabled=enabled
        )
        sync_generated_outputs(outputs, args.output.resolve(), check=args.check)
    except (GenerationError, GeneratedOutputError, OSError, ValueError) as error:
        print(
            f"Quake sky asset generation failed after {time.perf_counter() - started:.3f}s: {error}",
            file=sys.stderr,
        )
        return 1
    action = "verified" if args.check else "generated"
    print(
        f"Quake sky assets {action}: phases={len(outputs[PHASE_PATH])}, "
        f"outputs={len(outputs)}, sky={'enabled' if enabled else 'ordinary-texture'}, "
        f"elapsed={time.perf_counter() - started:.3f}s"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
