"""Quake alias package format and generated-source rendering."""

from __future__ import annotations

import struct

from quake_alias_packing import Location, cpu_load_address
from quake_billboard_assets import VIEW_COUNT
from quake_rom_config import MesenTarget
from quake_alias_animation import FLY_ROTATION_STEP_Q32


MAGIC = b"QBA1"
VERSION = 6
FLY_DIRECTIONAL_TAG = 0x8000
FLY_DIRECTIONAL_MASK = FLY_DIRECTIONAL_TAG - 1
HEADER = struct.Struct("<4s8H4IQ")
ROW_DIRECTORY = struct.Struct("<BBHBBH")
SPRITE_DIRECTORY = struct.Struct("<BBHBBBBBBhh")
STATE_RECORD = struct.Struct("<Hhhh")
FLY_FACING_RECORD = struct.Struct("<bb")
GROUP_HEADER = struct.Struct("<HHB")


def render_include(
    *,
    row_count: int,
    sprite_count: int,
    static_count: int,
    chunk_count: int,
    row_directory: Location,
    sprite_directory: Location,
    static_states: Location,
    fly_facing: Location,
    fly_facing_count: int,
    max_dynamic: int,
    max_visible: int,
    max_groups: int,
    fly_row: int,
    fly_row_count: int,
    mesen_target: MesenTarget,
    rotation: Location | None = None,
) -> bytes:
    lines = [
        "; Generated by generate_quake_alias_billboards.py; do not edit.",
        f"BSP_ALIAS_ASSET_VERSION = {VERSION}",
        "BSP_ALIAS_ENTITY_SUPPORTED = 1",
        f"BSP_ALIAS_ROW_COUNT = {row_count}",
        f"BSP_ALIAS_FLY_ROW = {fly_row}",
        f"BSP_ALIAS_FLY_ROW_COUNT = {fly_row_count}",
        f"BSP_ALIAS_VIEW_COUNT = {VIEW_COUNT}",
        f"BSP_ALIAS_SPRITE_COUNT = {sprite_count}",
        f"BSP_ALIAS_STATIC_STATE_COUNT = {static_count}",
        f"BSP_ALIAS_MAX_DYNAMIC_STATES = {max_dynamic}",
        f"BSP_ALIAS_MAX_VISIBLE_STATES = {max_visible}",
        f"BSP_ALIAS_MAX_GROUPS = {max_groups}",
        f"BSP_ALIAS_CHUNK_COUNT = {chunk_count}",
        f"BSP_ALIAS_GSU_ROM_MAX_BANK = ${mesen_target.max_gsu_rom_bank:02X}",
        f"BSP_ALIAS_ROW_RECORD_BYTES = {ROW_DIRECTORY.size}",
        f"BSP_ALIAS_SPRITE_RECORD_BYTES = {SPRITE_DIRECTORY.size}",
        f"BSP_ALIAS_STATE_RECORD_BYTES = {STATE_RECORD.size}",
        f"BSP_ALIAS_FLY_FACING_RECORD_BYTES = {FLY_FACING_RECORD.size}",
        f"BSP_ALIAS_FLY_FACING_COUNT = {fly_facing_count}",
        f"BSP_ALIAS_FLY_DIRECTIONAL_TAG = ${FLY_DIRECTIONAL_TAG:04X}",
        f"BSP_ALIAS_FLY_DIRECTIONAL_MASK = ${FLY_DIRECTIONAL_MASK:04X}",
        f"BSP_ALIAS_GROUP_HEADER_BYTES = {GROUP_HEADER.size}",
        f"BSP_ALIAS_ROW_DIRECTORY_BANK = ${row_directory.bank:02X}",
        f"BSP_ALIAS_ROW_DIRECTORY_ADDRESS = ${row_directory.address:04X}",
        f"BSP_ALIAS_SPRITE_DIRECTORY_BANK = ${sprite_directory.bank:02X}",
        f"BSP_ALIAS_SPRITE_DIRECTORY_ADDRESS = ${sprite_directory.address:04X}",
        f"BSP_ALIAS_STATIC_STATES_BANK = ${static_states.bank:02X}",
        f"BSP_ALIAS_STATIC_STATES_ADDRESS = ${static_states.address:04X}",
        f"BSP_ALIAS_FLY_FACING_BANK = ${fly_facing.bank:02X}",
        f"BSP_ALIAS_FLY_FACING_ADDRESS = ${fly_facing.address:04X}",
        "BSP_ALIAS_TOKEN_STATIC = $80",
        "",
    ]
    if rotation is not None:
        address = cpu_load_address(rotation.chunk) + rotation.offset
        lines.extend((
            f"BSP_ALIAS_ROTATION_BASES_CPU_ADDRESS = ${address:06X}",
            f"BSP_ALIAS_ROTATION_PHASES_CPU_ADDRESS = ${address + 512:06X}",
            f"BSP_ALIAS_ROTATION_STEP_Q32 = ${FLY_ROTATION_STEP_Q32:08X}",
            "BSP_ALIAS_ROTATION_SENTINEL = $FF80",
            "",
        ))
    return "\n".join(lines).encode("ascii")


def render_assembly(chunk_count: int) -> bytes:
    lines = ["; Generated by generate_quake_alias_billboards.py; do not edit."]
    for index in range(chunk_count):
        lines.extend(
            (
                f'.segment "BSP_ALIAS_{index}"',
                f"QuakeBSPAliasRuntime{index}:",
                f'        .incbin "Data/QuakeBSPAliasRuntime{index}.bin"',
                f"QuakeBSPAliasRuntime{index}End:",
                f'.assert QuakeBSPAliasRuntime{index}End - QuakeBSPAliasRuntime{index} = $8000, error, "Alias halfbank {index} size disagrees"',
                f'.assert __BSP_ALIAS_{index}_LOAD__ = ${cpu_load_address(index):06X}, lderror, "Alias halfbank {index} moved"',
                "",
            )
        )
    return "\n".join(lines).encode("ascii")
