#!/usr/bin/env python3
"""Publish canonical E1M3 inline-brush state from Quake's demo1 stream."""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from collections import defaultdict
from pathlib import Path
from typing import Any


TOOLS_DIR = Path(__file__).resolve().parent
SHARED_TOOLS_DIR = TOOLS_DIR.parents[1] / "shared" / "tools"
for dependency_dir in (TOOLS_DIR, SHARED_TOOLS_DIR):
    if str(dependency_dir) not in sys.path:
        sys.path.insert(0, str(dependency_dir))

from generated_outputs import (  # noqa: E402
    GeneratedOutputError,
    OwnedFileFamily,
    sync_generated_outputs,
)
import generate_quake_bsp as bsp_tools  # noqa: E402
from quake_bsp_brush_assets import build_brush_assets  # noqa: E402
from quake_brush_replay import (  # noqa: E402
    BRUSH_REPLAY_HEADER,
    BRUSH_REPLAY_SNAPSHOT,
    BRUSH_REPLAY_STATE,
    BRUSH_REPLAY_STEP_RATE_HZ,
    BRUSH_REPLAY_VERSION,
    BrushEntityState,
    CanonicalBrushReplay,
    decode_brush_replay,
    encode_precise_camera_track,
    encode_brush_replay,
    extract_canonical_brush_replay,
    fnv1a64,
    require_translation_only,
    step_row_indices,
)


DEFAULT_OUTPUT = TOOLS_DIR.parent / "Data"
STREAM_NAME = Path("QuakeBSPBrushReplay30Hz.bin")
METADATA_NAME = Path("QuakeBSPBrushReplay30Hz.json")
ASSET_METADATA_NAME = Path("QuakeBSPBrushAssets.json")
ASSET_INCLUDE_NAME = Path("QuakeBSPBrushAssets.i")
OWNED_OUTPUTS = (
    OwnedFileFamily(prefix="QuakeBSPBrushReplay", suffix=".bin"),
    OwnedFileFamily(prefix="QuakeBSPBrushReplay", suffix=".json"),
    OwnedFileFamily(prefix="QuakeBSPBrushAssets", suffix=".json"),
    OwnedFileFamily(prefix="QuakeBSPBrushAssets", suffix=".i"),
    OwnedFileFamily(prefix="QuakeBSPBrushRuntime", suffix=".bin", numbered=True),
    OwnedFileFamily(prefix="QuakeBSPBrushTexturePixels", suffix=".bin", numbered=True),
    OwnedFileFamily(prefix="QuakeBSPBrushFragments", suffix=".bin", numbered=True),
)
MOVING_BRUSH_CLASSES = ("func_button", "func_door", "func_plat", "func_train")


def asset_include(metadata: dict[str, Any]) -> bytes:
    runtime = metadata["runtime"]
    fragments = metadata["worldComposition"]["fragments"]
    roles = fragments["bankRoles"]
    lines = [
        "; Generated by generate_quake_brush_replay.py; do not edit.",
        f"BSP_BRUSH_ASSET_VERSION = {metadata['version']}",
        f"BSP_BRUSH_RUNTIME_FIRST_BANK = ${runtime['firstBank']:02X}",
        f"BSP_BRUSH_RUNTIME_BANK_COUNT = {runtime['bankCount']}",
        f"BSP_BRUSH_MODEL_COUNT = {metadata['geometry']['modelCount']}",
        f"BSP_BRUSH_FACE_COUNT = {metadata['geometry']['faceCount']}",
        f"BSP_BRUSH_INDEX_COUNT = {metadata['geometry']['indexCount']}",
        (
            "BSP_BRUSH_LIGHTMAPPED_TEXCOORD_AXIS_SPAN_Q4_MAX = "
            f"{metadata['lightmaps']['maximumTexcoordAxisSpanQ4']}"
        ),
        (
            "BSP_BRUSH_VISUAL_STATE_COUNT = "
            f"{metadata['visualStates']['visualStateCount']}"
        ),
        (f"BSP_BRUSH_ENTITY_ID_MAX = {metadata['visualStates']['maximumEntityId']}"),
        (
            "BSP_BRUSH_INLINE_MODEL_MAX = "
            f"{metadata['visualStates']['maximumInlineModel']}"
        ),
        "BSP_BRUSH_DISABLED_VISUAL_STATE = 0",
        f"BSP_BRUSH_REPLAY_ROW_COUNT = {metadata['replay']['rowCount']}",
        f"BSP_BRUSH_ENTITY_SLOT_COUNT = {metadata['replay']['entitySlotCount']}",
        f"BSP_BRUSH_VARIANT_COUNT = {metadata['replay']['variantCount']}",
        (
            "BSP_BRUSH_STATIC_BASELINE_COUNT = "
            f"{metadata['visualStates']['staticBaselineCount']}"
        ),
        (
            "BSP_BRUSH_REPLAY_LINK_MAX = "
            f"{metadata['visualStates']['fragmentLinkBounds']['replayMaximumNonSolidLinks']}"
        ),
        (
            "BSP_BRUSH_STATIC_LINK_COUNT = "
            f"{metadata['visualStates']['fragmentLinkBounds']['staticBaselineNonSolidLinks']}"
        ),
        (
            "BSP_BRUSH_FLY_LINK_MAX = "
            f"{metadata['visualStates']['fragmentLinkBounds']['flyCombinedMaximumNonSolidLinks']}"
        ),
        (
            "BSP_BRUSH_REPLAY_LEAF_MARKER_MAX = "
            f"{metadata['visualStates']['fragmentLinkBounds']['replayMaximumLeafMarkers']}"
        ),
        (
            "BSP_BRUSH_STATIC_LEAF_MARKER_COUNT = "
            f"{metadata['visualStates']['fragmentLinkBounds']['staticBaselineLeafMarkers']}"
        ),
        (
            "BSP_BRUSH_FLY_LEAF_MARKER_MAX = "
            f"{metadata['visualStates']['fragmentLinkBounds']['flyCombinedMaximumLeafMarkers']}"
        ),
        (
            "BSP_BRUSH_REPLAY_GROUP_FRAGMENT_MAX = "
            f"{metadata['visualStates']['fragmentLinkBounds']['replayMaximumLeafGroupFragments']}"
        ),
        (
            "BSP_BRUSH_REPLAY_GROUP_PROJECTED_VERTEX_MAX = "
            f"{metadata['visualStates']['fragmentLinkBounds']['replayMaximumLeafGroupProjectedVertices']}"
        ),
        (
            "BSP_BRUSH_FLY_GROUP_FRAGMENT_MAX = "
            f"{metadata['visualStates']['fragmentLinkBounds']['flyCombinedMaximumLeafGroupFragments']}"
        ),
        (
            "BSP_BRUSH_FLY_GROUP_PROJECTED_VERTEX_MAX = "
            f"{metadata['visualStates']['fragmentLinkBounds']['flyCombinedMaximumLeafGroupProjectedVertices']}"
        ),
        f"BSP_BRUSH_TEXTURE_COUNT = {metadata['textures']['extraTextureCount']}",
        (
            "BSP_BRUSH_MASKED_TEXTURE_COUNT = "
            f"{metadata['textures']['maskedTextureCount']}"
        ),
        f"BSP_BRUSH_TEXTURE_FIRST_BANK = ${metadata['capacity']['firstBrushBank']:02X}",
        f"BSP_BRUSH_TEXTURE_BANK_COUNT = {metadata['textures']['packedBankCount']}",
        "",
    ]
    for section in runtime["sections"]:
        prefix = f"BSP_BRUSH_{section['name']}"
        lines.extend(
            [
                f"{prefix}_BANK = ${section['bank']:02X}",
                f"{prefix}_ADDRESS = ${section['address']:04X}",
                f"{prefix}_BYTES = {section['bytes']}",
                f"{prefix}_RECORD_BYTES = {section['recordBytes']}",
                f"{prefix}_COUNT = {section['recordCount']}",
            ]
        )
    lines.extend(
        [
            "",
            f"BSP_BRUSH_FRAGMENT_FIRST_BANK = ${fragments['firstBank']:02X}",
            f"BSP_BRUSH_FRAGMENT_BANK_COUNT = {fragments['bankCount']}",
            f"BSP_BRUSH_FRAGMENT_VARIANT_COUNT = {fragments['variantCount']}",
            f"BSP_BRUSH_FRAGMENT_BUCKET_COUNT = {fragments['bucketCount']}",
            f"BSP_BRUSH_FRAGMENT_COUNT = {fragments['fragmentCount']}",
            (f"BSP_BRUSH_FRAGMENT_VERTEX_COUNT = {fragments['vertexOccurrenceCount']}"),
            (f"BSP_BRUSH_LEAF_HEAD_COUNT = {fragments['leafDomain']['headCount']}"),
            (
                "BSP_BRUSH_FRAGMENT_BUCKET_LEAF_MAX = "
                f"{fragments['leafDomain']['maximumBucketLeaf']}"
            ),
            (
                "BSP_BRUSH_SOLID_FALLBACK_LEAF = "
                f"{fragments['leafDomain']['solidFallbackLeaf']}"
            ),
            (
                "BSP_BRUSH_FRAGMENT_VARIANT_RECORD_BYTES = "
                f"{fragments['variantRecordBytes']}"
            ),
            (
                "BSP_BRUSH_FRAGMENT_BUCKET_RECORD_BYTES = "
                f"{fragments['bucketRecordBytes']}"
            ),
            (f"BSP_BRUSH_FRAGMENT_RECORD_BYTES = {fragments['fragmentRecordBytes']}"),
            (
                "BSP_BRUSH_FRAGMENT_FACE_RECORD_BYTES = "
                f"{fragments['faceMaterialRecordBytes']}"
            ),
            (
                "BSP_BRUSH_FRAGMENT_VERTEX_RECORD_BYTES = "
                f"{fragments['vertexRecordBytes']}"
            ),
            (
                "BSP_BRUSH_FRAGMENT_VARIANTS_ADDRESS = $"
                f"{0x8000 + roles['control']['variantOffset']:04X}"
            ),
            (
                "BSP_BRUSH_FRAGMENT_FACES_ADDRESS = $"
                f"{0x8000 + roles['control']['faceMaterialOffset']:04X}"
            ),
            (
                "BSP_BRUSH_FRAGMENT_BUCKETS_ADDRESS = $"
                f"{0x8000 + roles['control']['bucketOffset']:04X}"
            ),
            (
                "BSP_BRUSH_FRAGMENT_DESCRIPTORS_FIRST_BANK = $"
                f"{roles['descriptors']['firstBank']:02X}"
            ),
            (
                "BSP_BRUSH_FRAGMENT_DESCRIPTOR_BANK_COUNT = "
                f"{roles['descriptors']['bankCount']}"
            ),
            (
                "BSP_BRUSH_FRAGMENT_VERTICES_FIRST_BANK = $"
                f"{roles['vertices']['firstBank']:02X}"
            ),
            (
                "BSP_BRUSH_FRAGMENT_VERTEX_BANK_COUNT = "
                f"{roles['vertices']['bankCount']}"
            ),
            (
                "BSP_BRUSH_SOLID_LEAF_COUNT = "
                f"{metadata['worldComposition']['solidLeafCount']}"
            ),
            (f"BSP_BRUSH_LEAF_COUNT = {metadata['worldComposition']['leafCount']}"),
            "",
        ]
    )
    return "\n".join(lines).encode("ascii")


def inline_entity_definitions(bsp: bytes) -> dict[int, dict[str, str]]:
    lumps = bsp_tools.lump_ranges(bsp)
    entities = bsp_tools.parse_entities(
        bsp_tools.lump_data(bsp, lumps, bsp_tools.LUMP_ENTITIES)
    )
    result: dict[int, dict[str, str]] = {}
    for entity in entities:
        model = entity.get("model", "")
        if not model.startswith("*") or not model[1:].isdigit():
            continue
        model_id = int(model[1:])
        if model_id <= 0 or model_id in result:
            raise ValueError(f"invalid or duplicate BSP inline model {model!r}")
        result[model_id] = entity
    return result


def _state_summary(
    entity: int,
    states: list[tuple[int, BrushEntityState]],
    definitions: dict[int, dict[str, str]],
) -> dict[str, Any]:
    model_ids = sorted({state.inline_model for _row, state in states})
    if len(model_ids) != 1:
        raise ValueError(f"entity {entity} changes inline model in the replay")
    model_id = model_ids[0]
    definition = definitions.get(model_id, {})
    origins = sorted({state.origin for _row, state in states})
    frames = sorted({state.frame for _row, state in states})
    angles = sorted({state.angles for _row, state in states})
    return {
        "entity": entity,
        "inlineModel": model_id,
        "classname": definition.get("classname", ""),
        "firstRow": states[0][0],
        "lastRow": states[-1][0],
        "activeRowCount": len(states),
        "originStateCount": len(origins),
        "originMinimum": [min(origin[axis] for origin in origins) for axis in range(3)],
        "originMaximum": [max(origin[axis] for origin in origins) for axis in range(3)],
        "frames": frames,
        "angles": [list(angle) for angle in angles],
    }


def replay_audit(
    replay: CanonicalBrushReplay,
    definitions: dict[int, dict[str, str]],
) -> dict[str, Any]:
    observations: dict[int, list[tuple[int, BrushEntityState]]] = defaultdict(list)
    for row in replay.rows:
        for state in row.brushes:
            observations[state.entity_number].append((row.index, state))
    entities = [
        _state_summary(entity, states, definitions)
        for entity, states in sorted(observations.items())
    ]
    translating = [entry for entry in entities if entry["originStateCount"] > 1]
    frame_changing = [entry for entry in entities if len(entry["frames"]) > 1]
    angled = [
        entry
        for entry in entities
        if any(angle != [0.0, 0.0, 0.0] for angle in entry["angles"])
    ]
    class_counts: dict[str, int] = {classname: 0 for classname in MOVING_BRUSH_CLASSES}
    for entry in translating:
        classname = entry["classname"]
        class_counts[classname] = class_counts.get(classname, 0) + 1
    signon_models = {state.inline_model for state in replay.signon_brushes}
    return {
        "signon": {
            "brushEntityCount": len(replay.signon_brushes),
            "inlineModelCount": len(signon_models),
        },
        "everActive": {
            "brushEntityCount": len(entities),
            "inlineModelCount": len({entry["inlineModel"] for entry in entities}),
            "entities": entities,
        },
        "perRow": {
            "minimumActive": min(len(row.brushes) for row in replay.rows),
            "maximumActive": max(len(row.brushes) for row in replay.rows),
            "totalActiveStates": sum(len(row.brushes) for row in replay.rows),
        },
        "translating": {
            "entityCount": len(translating),
            "byClass": dict(sorted(class_counts.items())),
            "entities": translating,
        },
        "frameChanging": {
            "entityCount": len(frame_changing),
            "entities": frame_changing,
        },
        "nonzeroAngle": {
            "entityCount": len(angled),
            "entities": angled,
        },
    }


def build_outputs(pak_path: Path) -> tuple[dict[Path, bytes], dict[str, Any]]:
    archive = bsp_tools.PakArchive(pak_path)
    demo = archive.read(bsp_tools.DEMO_ENTRY)
    bsp = archive.read(bsp_tools.BSP_ENTRY)
    palette = archive.read(bsp_tools.PALETTE_ENTRY)
    replay = extract_canonical_brush_replay(demo, bsp_tools.BSP_ENTRY)
    require_translation_only(replay)
    payload = encode_brush_replay(replay)
    precise_camera_track = encode_precise_camera_track(replay.rows)
    camera_track_fingerprint = fnv1a64(precise_camera_track)
    if camera_track_fingerprint != replay.camera_track_fnv1a64:
        raise AssertionError("canonical camera fingerprint is inconsistent")
    decoded = decode_brush_replay(payload)
    expected_rows = tuple(row.brushes for row in replay.rows)
    if decoded.rows != expected_rows:
        raise AssertionError("brush replay codec does not round-trip losslessly")
    steps = step_row_indices(len(replay.rows))
    audit = replay_audit(replay, inline_entity_definitions(bsp))
    metadata: dict[str, Any] = {
        "schema": "quake-bsp-brush-replay",
        "version": BRUSH_REPLAY_VERSION,
        "source": {
            "pakPathHint": bsp_tools.QUAKE_PAK_PATH_HINT,
            "mapEntry": bsp_tools.BSP_ENTRY,
            "demoEntry": bsp_tools.DEMO_ENTRY,
            "bspSha256": hashlib.sha256(bsp).hexdigest(),
            "demoSha256": hashlib.sha256(demo).hexdigest(),
        },
        "timeline": {
            "contract": "newest source camera and entity snapshot due; no interpolation",
            "sampleRateHz": replay.sample_rate_hz,
            "firstSourceServerTime": replay.first_server_time,
            "textureAnimationClock": (
                "firstSourceServerTime + rowIndex / sampleRateHz"
            ),
            "cameraTrackFnv1a64": f"{camera_track_fingerprint:016x}",
            "cameraTrackSha256": hashlib.sha256(precise_camera_track).hexdigest(),
            "sourceCameraSamples": replay.source_sample_count,
            "rowCount": len(replay.rows),
            "firstRow": replay.rows[0].index,
            "lastRow": replay.rows[-1].index,
            "stepSampleRateHz": BRUSH_REPLAY_STEP_RATE_HZ,
            "stepStride": replay.sample_rate_hz // BRUSH_REPLAY_STEP_RATE_HZ,
            "stepRowCount": len(steps),
            "stepFirstRow": steps[0],
            "stepLastRow": steps[-1],
        },
        "format": {
            "magic": "QBR2",
            "headerBytes": BRUSH_REPLAY_HEADER.size,
            "snapshotDirectoryRecordBytes": BRUSH_REPLAY_SNAPSHOT.size,
            "entityStateBytes": BRUSH_REPLAY_STATE.size,
            "activeStateEncoding": "full active set per deduplicated snapshot",
            "coordinateEncoding": "signed Q3",
            "angleEncoding": "protocol signed byte",
        },
        "audit": audit,
        "output": {
            "path": STREAM_NAME.as_posix(),
            "bytes": len(payload),
            "sha256": hashlib.sha256(payload).hexdigest(),
            "uniqueSnapshotCount": len({row.brushes for row in replay.rows}),
        },
    }
    rendered_metadata = (json.dumps(metadata, indent=2, sort_keys=True) + "\n").encode(
        "ascii"
    )
    assets = build_brush_assets(bsp, palette, replay)
    asset_metadata = {
        **assets.metadata,
        "source": {
            **assets.metadata["source"],
            "pakPathHint": bsp_tools.QUAKE_PAK_PATH_HINT,
            "mapEntry": bsp_tools.BSP_ENTRY,
            "demoEntry": bsp_tools.DEMO_ENTRY,
            "demoSha256": hashlib.sha256(demo).hexdigest(),
        },
        "canonicalSourceReplay": {
            "path": STREAM_NAME.as_posix(),
            "bytes": len(payload),
            "sha256": hashlib.sha256(payload).hexdigest(),
        },
    }
    include_payload = asset_include(asset_metadata)
    asset_metadata["outputs"][ASSET_INCLUDE_NAME.as_posix()] = {
        "bytes": len(include_payload),
        "sha256": hashlib.sha256(include_payload).hexdigest(),
    }
    rendered_asset_metadata = (
        json.dumps(asset_metadata, indent=2, sort_keys=True) + "\n"
    ).encode("ascii")
    return {
        STREAM_NAME: payload,
        METADATA_NAME: rendered_metadata,
        ASSET_METADATA_NAME: rendered_asset_metadata,
        ASSET_INCLUDE_NAME: include_payload,
        **assets.outputs,
    }, metadata


def write_or_check(outputs: dict[Path, bytes], output: Path, check: bool) -> None:
    try:
        sync_generated_outputs(
            outputs,
            output,
            check=check,
            owned_families=OWNED_OUTPUTS,
        )
    except GeneratedOutputError as error:
        raise SystemExit(f"generated Quake brush replay is stale:\n{error}") from None


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--pak", type=Path)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    outputs, metadata = build_outputs(bsp_tools.locate_quake_pak(args.pak))
    write_or_check(outputs, args.output, args.check)
    audit = metadata["audit"]
    action = "verified" if args.check else "generated"
    print(
        f"{action} {metadata['timeline']['rowCount']} aligned brush rows; "
        f"{audit['everActive']['brushEntityCount']} entities ever active, "
        f"{audit['translating']['entityCount']} translate, "
        f"{audit['frameChanging']['entityCount']} change frame; "
        "packed 57 signon models"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
