#!/usr/bin/env python3
"""Generate compact E1M3 monster eye-level camera placements for the SNES ROM."""

from __future__ import annotations

import argparse
import hashlib
import json
import struct
import sys
from pathlib import Path
from typing import Any


TOOLS = Path(__file__).resolve().parent
EXAMPLE = TOOLS.parent
SHARED = EXAMPLE.parent / "shared/tools"
sys.path[:0] = [str(TOOLS), str(SHARED)]

from generate_quake_bsp import (  # noqa: E402
    BSP_ENTRY,
    LUMP_ENTITIES,
    PakArchive,
    locate_quake_pak,
    lump_data,
    lump_ranges,
    parse_entities,
)
from generated_outputs import GeneratedOutputError, sync_generated_outputs  # noqa: E402
from quake_demo import DEFAULT_VIEWHEIGHT  # noqa: E402


DEFAULT_OUTPUT = EXAMPLE / "Data"
DEFAULT_METADATA = DEFAULT_OUTPUT / "QuakeBSPMetadata.json"
TABLE_PATH = Path("QuakeBSPMonsterCameras.bin")
CONSTANTS_PATH = Path("QuakeBSPMonsterCameras.i")
REPORT_PATH = Path("QuakeBSPMonsterCameras.json")
MONSTER_PREFIX = "monster_"
CAMERA_Q8_PER_QUAKE_UNIT = 16
YAW_STEPS = 32
RECORD_BYTES = 8


def parse_origin(entity: dict[str, str]) -> tuple[float, float, float]:
    fields = tuple(float(field) for field in entity.get("origin", "").split())
    if len(fields) != 3:
        raise ValueError(f"{entity.get('classname', 'monster')} has no XYZ origin")
    return fields


def camera_q8(
    origin: tuple[float, float, float],
    world_origin: tuple[float, float, float],
) -> tuple[int, int, int]:
    eye_origin = (origin[0], origin[1], origin[2] + DEFAULT_VIEWHEIGHT)
    values = tuple(
        round((value - base) * CAMERA_Q8_PER_QUAKE_UNIT)
        for value, base in zip(eye_origin, world_origin, strict=True)
    )
    if any(not -0x8000 <= value <= 0x7FFF for value in values):
        raise ValueError(f"monster camera eye escapes signed Q8 storage: {eye_origin}")
    return values


def yaw_index(angle: float) -> int:
    if angle < 0:
        raise ValueError(f"special vertical entity angle is not a monster yaw: {angle}")
    return round((angle % 360.0) * YAW_STEPS / 360.0) & (YAW_STEPS - 1)


def generate(
    entities: list[dict[str, str]],
    world_origin: tuple[float, float, float],
) -> tuple[dict[Path, bytes], dict[str, Any]]:
    records: list[bytes] = []
    placements: list[dict[str, Any]] = []
    class_counts: dict[str, int] = {}
    for entity_index, entity in enumerate(entities):
        classname = entity.get("classname", "")
        if not classname.startswith(MONSTER_PREFIX):
            continue
        origin = parse_origin(entity)
        eye_origin = (origin[0], origin[1], origin[2] + DEFAULT_VIEWHEIGHT)
        angle = float(entity.get("angle", "0"))
        packed_camera = camera_q8(origin, world_origin)
        packed_yaw = yaw_index(angle)
        records.append(
            struct.pack(
                "<hhhh",
                packed_camera[0],
                packed_camera[1],
                packed_camera[2],
                packed_yaw,
            )
        )
        class_counts[classname] = class_counts.get(classname, 0) + 1
        placements.append(
            {
                "cameraQ8": list(packed_camera),
                "classname": classname,
                "entityIndex": entity_index,
                "eyeOrigin": list(eye_origin),
                "origin": list(origin),
                "spawnflags": int(entity.get("spawnflags", "0")),
                "yawDegrees": angle,
                "yawIndex": packed_yaw,
            }
        )

    if not records:
        raise ValueError("E1M3 contains no monster camera placements")
    table = b"".join(records)
    constants = (
        "; Generated by tools/generate_quake_monster_cameras.py. Do not edit.\n"
        f"BSP_MONSTER_CAMERA_COUNT = {len(records)}\n"
        f"BSP_MONSTER_CAMERA_RECORD_BYTES = {RECORD_BYTES}\n"
    ).encode("ascii")
    report: dict[str, Any] = {
        "schema": "quake-bsp-monster-cameras-v2",
        "source": {
            "defaultViewHeight": DEFAULT_VIEWHEIGHT,
            "mapEntry": BSP_ENTRY,
            "monsterPrefix": MONSTER_PREFIX,
            "worldOrigin": list(world_origin),
        },
        "packing": {
            "cameraQ8PerQuakeUnit": CAMERA_Q8_PER_QUAKE_UNIT,
            "recordBytes": RECORD_BYTES,
            "yawSteps": YAW_STEPS,
        },
        "count": len(records),
        "classCounts": dict(sorted(class_counts.items())),
        "placements": placements,
        "table": {
            "bytes": len(table),
            "sha256": hashlib.sha256(table).hexdigest(),
        },
    }
    outputs = {
        TABLE_PATH: table,
        CONSTANTS_PATH: constants,
        REPORT_PATH: (
            json.dumps(report, indent=2, sort_keys=True) + "\n"
        ).encode("ascii"),
    }
    return outputs, report


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--pak", type=Path)
    parser.add_argument("--metadata", type=Path, default=DEFAULT_METADATA)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)

    metadata = json.loads(args.metadata.read_text(encoding="ascii"))
    world_origin = tuple(
        float(value) for value in metadata["world"]["quantization"]["origin"]
    )
    if len(world_origin) != 3 or metadata["source"]["pak_entry"] != BSP_ENTRY:
        raise ValueError("SNES Quake metadata does not describe the E1M3 world")
    archive = PakArchive(locate_quake_pak(args.pak))
    bsp = archive.read(BSP_ENTRY)
    entities = parse_entities(lump_data(bsp, lump_ranges(bsp), LUMP_ENTITIES))
    outputs, report = generate(entities, world_origin)
    try:
        sync_generated_outputs(outputs, args.output, check=args.check)
    except GeneratedOutputError as error:
        raise SystemExit(f"generated monster cameras are stale:\n{error}") from None
    action = "verified" if args.check else "generated"
    print(
        f"{action} {report['count']} monster camera placements "
        f"in {report['table']['bytes']} bytes"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
